from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from .acceptance import apply_metric_thresholds
from .code_contract import rtc_source_tree_sha256


def _sha(path: str | Path) -> str:
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def create_gate(
    *,
    metrics_path: str | Path,
    contract_path: str | Path,
    section: str,
    output_path: str | Path,
) -> dict[str, object]:
    metrics_payload = json.loads(Path(metrics_path).read_text(encoding="utf-8"))
    contract = json.loads(Path(contract_path).read_text(encoding="utf-8"))
    if not isinstance(metrics_payload, dict) or not isinstance(contract, dict):
        raise ValueError("metrics/acceptance contract must be JSON objects")
    current_code = rtc_source_tree_sha256()
    if metrics_payload.get("rtc_source_tree_sha256") != current_code:
        raise ValueError(
            "raw metrics were generated by a different RTC source tree; regenerate the metrics"
        )
    raw = contract.get(section)
    if not isinstance(raw, dict):
        raise ValueError(f"acceptance contract lacks section {section}")
    minimum = {str(k): float(v) for k, v in raw.get("minimum", {}).items()}
    maximum = {str(k): float(v) for k, v in raw.get("maximum", {}).items()}
    metrics = metrics_payload.get("metrics")
    if not isinstance(metrics, dict):
        raise ValueError("metrics evidence lacks metrics object")
    result = apply_metric_thresholds(
        {str(k): float(v) for k, v in metrics.items()},
        minimum=minimum,
        maximum=maximum,
    )
    source_contract = str(metrics_payload.get("contract", ""))
    if not source_contract:
        raise ValueError("metrics evidence lacks an explicit source contract")
    payload: dict[str, object] = {
        "contract": "PREREGISTERED_ACCEPTANCE_GATE_V4_SOURCE_BOUND",
        "section": section,
        "passed": result.passed,
        "failed_metrics": list(result.failed_metrics),
        "metrics": result.metrics,
        "thresholds": {"minimum": minimum, "maximum": maximum},
        "source_metrics_contract": source_contract,
        "source_metrics_path": str(Path(metrics_path)),
        "source_metrics_sha256": _sha(metrics_path),
        "source_metrics_aggregation": metrics_payload.get("aggregation"),
        "acceptance_contract_path": str(Path(contract_path)),
        "acceptance_contract_sha256": _sha(contract_path),
        "rtc_source_tree_sha256": current_code,
    }
    for key in (
        "model_sha256",
        "step2_sha256",
        "manifest_sha256",
        "model_step_seconds",
        "horizon_steps",
    ):
        if key in metrics_payload:
            payload[key] = metrics_payload[key]
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return payload


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Apply frozen thresholds to current-code raw metrics only"
    )
    parser.add_argument("--metrics", required=True)
    parser.add_argument("--contract", required=True)
    parser.add_argument("--section", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()
    payload = create_gate(
        metrics_path=args.metrics,
        contract_path=args.contract,
        section=args.section,
        output_path=args.out,
    )
    print(json.dumps(payload, indent=2))
    if not payload["passed"]:
        raise SystemExit(2)


if __name__ == "__main__":
    main()
