"""Optimizer-matched one-sided admission for the refined executable first move.

V10 showed that a scalar margin inherited from a different estimand can make every receding decision
HOLD even when most rejected first moves are authoritatively beneficial.  This module calibrates only
on SWMM labels generated by the *same refined first-move query* used online.  No generic D3 full-plan
floor, V9 full-plan margin, or V10 prefix floor is allowed to control execution.

The independent conformal unit remains the rainfall group.  The current Development contract requires
at least 24 fresh calibration rainfall groups so 90% split-conformal no longer degenerates to the
maximum residual of a ten-group panel.
"""
from __future__ import annotations

import math
from collections import defaultdict
from typing import Any, Mapping, Sequence

from .direct_tfv_admission import DIRECT_TFV_ADMISSION_COVERAGE, _one_sided_conformal_upper
from .direct_tfv_first_move import DIRECT_TFV_FIRST_MOVE_SEMANTICS


DIRECT_TFV_FIRST_MOVE_PANEL_CONTRACT = (
    "PROJECT7_DIRECT_TFV_REFINED_FIRST_MOVE_CALIBRATION_PANEL_V1"
)
DIRECT_TFV_FIRST_MOVE_ADMISSION_CONTRACT = (
    "PROJECT7_DIRECT_TFV_REFINED_FIRST_MOVE_ONE_SIDED_ADMISSION_V1"
)
DIRECT_TFV_FIRST_MOVE_QUERY_STEP3_CONTRACT = (
    "PROJECT7_DIRECT_TFV_109ACT_RECEDING_MPC_V9"
)
DIRECT_TFV_FIRST_MOVE_MIN_CALIBRATION_GROUPS = 24


def _finite(value: Any, *, label: str) -> float:
    result = float(value)
    if not math.isfinite(result):
        raise ValueError(f"{label} must be finite")
    return result


def derive_first_move_admission(
    *,
    panel_contract: str,
    panel_step3_contract: str,
    panel_records: Sequence[Mapping[str, Any]],
    expected_rainfall_groups: Sequence[str],
    coverage: float = DIRECT_TFV_ADMISSION_COVERAGE,
) -> dict[str, Any]:
    """Derive the one-sided residual margin for refined H10-then-HOLD queries."""

    if str(panel_contract) != DIRECT_TFV_FIRST_MOVE_PANEL_CONTRACT:
        raise ValueError("first-move calibration panel has the wrong contract")
    if str(panel_step3_contract) != DIRECT_TFV_FIRST_MOVE_QUERY_STEP3_CONTRACT:
        raise ValueError("first-move calibration panel was generated by a different optimizer")
    if not 0.5 < float(coverage) < 1.0:
        raise ValueError("first-move admission coverage must lie in (0.5,1)")
    expected = {str(value) for value in expected_rainfall_groups if str(value)}
    if len(expected) < DIRECT_TFV_FIRST_MOVE_MIN_CALIBRATION_GROUPS:
        raise ValueError(
            "refined first-move admission requires at least "
            f"{DIRECT_TFV_FIRST_MOVE_MIN_CALIBRATION_GROUPS} fresh rainfall groups; got {len(expected)}"
        )

    by_group: dict[str, list[float]] = defaultdict(list)
    plan_hashes: set[str] = set()
    changed_counts: list[int] = []
    for row in panel_records:
        group = str(row.get("rainfall_group", ""))
        if group not in expected:
            raise ValueError(f"first-move panel contains non-calibration rainfall group: {group!r}")
        plan_sha = str(row.get("plan_sha256", ""))
        if not plan_sha or plan_sha in plan_hashes:
            raise ValueError("first-move panel requires unique non-empty plan SHA values")
        plan_hashes.add(plan_sha)
        predicted = _finite(
            row.get("predicted_refined_delta_tfv_m3"),
            label="predicted refined first-move delta TFV",
        )
        truth = _finite(
            row.get("true_refined_delta_tfv_m3"),
            label="true refined first-move delta TFV",
        )
        by_group[group].append(truth - predicted)
        changed = int(row.get("first_move_changed_facility_count", -1))
        if changed < 0 or changed > 109:
            raise ValueError("first-move panel has invalid changed-facility count")
        changed_counts.append(changed)

    if set(by_group) != expected:
        raise ValueError(
            "first-move calibration must cover every expected rainfall group; "
            f"missing={sorted(expected-set(by_group))}, extra={sorted(set(by_group)-expected)}"
        )
    group_max = {group: max(values) for group, values in by_group.items() if values}
    margin = max(0.0, _one_sided_conformal_upper(list(group_max.values()), float(coverage)))
    ordered = sorted(float(value) for value in group_max.values())
    return {
        "contract": DIRECT_TFV_FIRST_MOVE_ADMISSION_CONTRACT,
        "development_only": True,
        "execution_estimand": DIRECT_TFV_FIRST_MOVE_SEMANTICS,
        "coverage": float(coverage),
        "independent_unit": "RAINFALL_GROUP_MAX_TRUE_MINUS_PREDICTED_RESIDUAL",
        "residual_definition": "true_refined_delta_tfv_m3_minus_predicted_refined_delta_tfv_m3",
        "admission_rule": "predicted_refined_delta_tfv_m3 + refined_first_move_margin_m3 < 0",
        "global_margin_m3": float(margin),
        "calibration_rainfall_group_count": len(group_max),
        "calibration_rainfall_groups": sorted(group_max),
        "calibration_plan_count": len(panel_records),
        "query_step3_contract": DIRECT_TFV_FIRST_MOVE_QUERY_STEP3_CONTRACT,
        "generic_d3_floor_controls_execution": False,
        "v9_full_plan_margin_controls_execution": False,
        "v10_prefix_margin_controls_execution": False,
        "minimum_calibration_rainfall_groups": DIRECT_TFV_FIRST_MOVE_MIN_CALIBRATION_GROUPS,
        "group_residual_min_m3": float(ordered[0]),
        "group_residual_median_m3": float(ordered[len(ordered) // 2]),
        "group_residual_max_m3": float(ordered[-1]),
        "changed_facility_count_min": min(changed_counts, default=0),
        "changed_facility_count_max": max(changed_counts, default=0),
        "online_swmm_called": False,
        "scientific_role": (
            "Execution uncertainty is calibrated only on fresh authoritative SWMM labels of the "
            "same shrink-only refined first-move optimizer used online. Historical full-plan and "
            "generic-D3 margins are retained only as diagnostics."
        ),
    }


def first_move_margin_m3(calibration: Mapping[str, Any]) -> float:
    if str(calibration.get("contract", "")) != DIRECT_TFV_FIRST_MOVE_ADMISSION_CONTRACT:
        raise ValueError("Direct-TFV refined first move received the wrong admission contract")
    value = _finite(calibration.get("global_margin_m3"), label="first-move margin")
    if value < 0.0:
        raise ValueError("first-move margin must be non-negative")
    return float(value)


__all__ = [
    "DIRECT_TFV_FIRST_MOVE_ADMISSION_CONTRACT",
    "DIRECT_TFV_FIRST_MOVE_MIN_CALIBRATION_GROUPS",
    "DIRECT_TFV_FIRST_MOVE_PANEL_CONTRACT",
    "DIRECT_TFV_FIRST_MOVE_QUERY_STEP3_CONTRACT",
    "derive_first_move_admission",
    "first_move_margin_m3",
]
