"""Step3 V19 zero-anchored query-conditioned exact policy-return advantage model.

V14--V18 repeatedly separated candidate ranking from the ACTION/HOLD decision but still treated
the selected-candidate boundary as either a generic deep classifier or an additive compact classifier.
This module encodes the actual estimand directly: advantage is produced only by candidate-minus-HOLD
action effects and their interaction with the current causal query context.

Structural identity:
    candidate == HOLD/reference  -> design vector == 0 -> predicted advantage == 0

The frozen V15 rank remains responsible for candidate ordering. V19 only estimates the absolute
selected-candidate exact receding-policy-return versus HOLD. No Step1/Step2 weights are changed and
no SWMM truth is generated by this module.
"""
from __future__ import annotations

from dataclasses import dataclass
import math
from pathlib import Path
from typing import Any

import numpy as np
import torch
from torch import nn

from .checkpoint_direct_tfv import load_direct_tfv_runtime_checkpoint
from .direct_tfv_policy_return import sha256_file
from .direct_tfv_policy_return_portfolio_admission import CURRENT_THREE_FAMILY_SOURCES
from .direct_tfv_policy_return_query_margin_v17 import (
    LEGACY_V15_CHECKPOINT_CONTRACT,
    QueryConditionedPolicyReturnAdapterV17,
    import_v15_rank_state,
)


DIRECT_TFV_ADVANTAGE_V19_CONTRACT = (
    "PROJECT7_STEP3_ADVANTAGE_V19_ZERO_ANCHORED_CONTEXT_ACTION_INTERACTION"
)
DIRECT_TFV_ADVANTAGE_V19_CHECKPOINT_CONTRACT = (
    "PROJECT7_STEP3_ADVANTAGE_V19_CHECKPOINT_ZERO_ANCHORED_ALL_RECORDS"
)
DIRECT_TFV_ADVANTAGE_V19_FEATURE_CONTRACT = (
    "FROZEN_STEP2_ACTION_MINUS_HOLD_LATENT_LOW_RANK_CONTEXT_INTERACTION_V1"
)

CONTEXT_COMPONENTS = 4
ACTION_COMPONENTS = 6
LEGACY_CANDIDATE_WIDTH = 9
EXPLICIT_INTERACTION_DIM = 5
ADVANTAGE_COORDINATE_MAX = 6.0


@dataclass(frozen=True)
class ZeroAnchoredAdvantagePartsV19:
    """Raw feature blocks used by the zero-anchored advantage preprocessor."""

    context: torch.Tensor
    action_dense: torch.Tensor
    explicit: torch.Tensor


@dataclass(frozen=True)
class AdvantagePredictionV19:
    """Numeric advantage prediction under the exact candidate-vs-HOLD sign convention."""

    coordinate: torch.Tensor
    advantage_m3: torch.Tensor
    execute: torch.Tensor


def _source_gate(
    source: str,
    *,
    action_mass: torch.Tensor,
    dtype: torch.dtype,
    device: torch.device,
) -> torch.Tensor:
    allowed = tuple(CURRENT_THREE_FAMILY_SOURCES)
    if source not in allowed:
        raise ValueError(f"V19 received non-current candidate family: {source}")
    gate = torch.zeros(len(allowed), dtype=dtype, device=device)
    gate[allowed.index(source)] = action_mass
    return gate


def build_zero_anchored_advantage_parts_v19(
    *,
    context_features: torch.Tensor,
    candidate_features: torch.Tensor,
    raw_step2_score_m3: torch.Tensor,
    active_target: torch.Tensor,
    candidate_target: torch.Tensor,
    candidate_source: str,
    supervisory_mask: np.ndarray | torch.Tensor,
    target_scale_m3: float,
) -> ZeroAnchoredAdvantagePartsV19:
    """Build action-to-HOLD features that vanish identically for a HOLD action."""
    if context_features.ndim != 1:
        raise ValueError("V19 context features must be one-dimensional")
    if candidate_features.ndim != 1 or int(candidate_features.numel()) <= LEGACY_CANDIDATE_WIDTH:
        raise ValueError("V19 candidate feature width is incompatible with the frozen V15 feature contract")
    if tuple(active_target.shape) != (109,) or tuple(candidate_target.shape) != (109,):
        raise ValueError("V19 requires 109-channel active/candidate targets")
    mask = torch.as_tensor(
        supervisory_mask,
        dtype=torch.bool,
        device=candidate_target.device,
    ).reshape(-1)
    if tuple(mask.shape) != (109,) or int(mask.sum()) != 82:
        raise ValueError("V19 requires the frozen 82/109 supervisory mask")
    scale = float(target_scale_m3)
    if not math.isfinite(scale) or scale <= 0.0:
        raise ValueError("V19 target scale must be finite and positive")

    passive = ~mask
    if bool(torch.any(torch.abs(candidate_target[passive] - active_target[passive]) > 1.0e-7)):
        raise ValueError("V19 candidate changed a passive/reference-only channel")

    delta = candidate_target[mask] - active_target[mask]
    abs_delta = torch.abs(delta)
    active = bool(torch.any(abs_delta > 1.0e-7))
    dtype = candidate_features.dtype
    device = candidate_features.device

    if not active:
        action_dense = torch.zeros(
            int(candidate_features.numel()) - LEGACY_CANDIDATE_WIDTH,
            dtype=dtype,
            device=device,
        )
        explicit = torch.zeros(11, dtype=dtype, device=device)
        return ZeroAnchoredAdvantagePartsV19(
            context=context_features,
            action_dense=action_dense,
            explicit=explicit,
        )

    action_dense = candidate_features[LEGACY_CANDIDATE_WIDTH:].clone()
    changed_fraction = torch.count_nonzero(abs_delta > 1.0e-7).to(dtype) / 82.0
    mean_abs = abs_delta.mean()
    max_abs = abs_delta.amax()
    rms = torch.sqrt(torch.mean(torch.square(delta)).clamp_min(0.0))
    signed_mean = delta.mean()
    positive_mean = torch.clamp(delta, min=0.0).mean()
    negative_mean = torch.clamp(-delta, min=0.0).mean()
    raw_norm = raw_step2_score_m3.reshape(()).to(dtype=dtype, device=device) / scale
    family_gate = _source_gate(
        str(candidate_source),
        action_mass=rms,
        dtype=dtype,
        device=device,
    )
    explicit = torch.cat(
        (
            torch.stack(
                (
                    raw_norm,
                    changed_fraction,
                    mean_abs,
                    max_abs,
                    rms,
                    signed_mean,
                    positive_mean,
                    negative_mean,
                )
            ),
            family_gate,
        ),
        dim=0,
    )
    if tuple(explicit.shape) != (11,):
        raise RuntimeError("V19 explicit feature width drifted")
    if not bool(torch.isfinite(action_dense).all()) or not bool(torch.isfinite(explicit).all()):
        raise RuntimeError("V19 action-to-HOLD features contain non-finite values")
    return ZeroAnchoredAdvantagePartsV19(
        context=context_features,
        action_dense=action_dense,
        explicit=explicit,
    )


class ZeroAnchoredAdvantagePreprocessorV19(nn.Module):
    """Train-only low-rank context/action preprocessing with an exact zero action anchor."""

    def __init__(
        self,
        *,
        context_mean: torch.Tensor,
        context_std: torch.Tensor,
        context_components: torch.Tensor,
        action_scale: torch.Tensor,
        action_components: torch.Tensor,
        explicit_scale: torch.Tensor,
    ) -> None:
        super().__init__()
        if context_mean.ndim != 1 or context_std.shape != context_mean.shape:
            raise ValueError("V19 context standardization shape mismatch")
        if context_components.ndim != 2 or int(context_components.shape[1]) != int(context_mean.numel()):
            raise ValueError("V19 context PCA shape mismatch")
        if action_scale.ndim != 1:
            raise ValueError("V19 action scale must be one-dimensional")
        if action_components.ndim != 2 or int(action_components.shape[1]) != int(action_scale.numel()):
            raise ValueError("V19 action PCA shape mismatch")
        if explicit_scale.ndim != 1 or int(explicit_scale.numel()) < EXPLICIT_INTERACTION_DIM:
            raise ValueError("V19 explicit scale width mismatch")
        self.register_buffer("context_mean", context_mean.detach().to(torch.float32))
        self.register_buffer("context_std", context_std.detach().to(torch.float32).clamp_min(1.0e-6))
        self.register_buffer(
            "context_components",
            context_components.detach().to(torch.float32),
        )
        self.register_buffer("action_scale", action_scale.detach().to(torch.float32).clamp_min(1.0e-6))
        self.register_buffer(
            "action_components",
            action_components.detach().to(torch.float32),
        )
        self.register_buffer("explicit_scale", explicit_scale.detach().to(torch.float32).clamp_min(1.0e-6))

    @property
    def output_dim(self) -> int:
        context_dim = int(self.context_components.shape[0])
        action_dim = int(self.action_components.shape[0])
        explicit_dim = int(self.explicit_scale.numel())
        return (
            action_dim
            + explicit_dim
            + context_dim * action_dim
            + context_dim * EXPLICIT_INTERACTION_DIM
        )

    def forward(self, parts: ZeroAnchoredAdvantagePartsV19) -> torch.Tensor:
        context = parts.context.to(
            dtype=self.context_mean.dtype,
            device=self.context_mean.device,
        )
        action = parts.action_dense.to(
            dtype=self.action_scale.dtype,
            device=self.action_scale.device,
        )
        explicit = parts.explicit.to(
            dtype=self.explicit_scale.dtype,
            device=self.explicit_scale.device,
        )
        if tuple(context.shape) != tuple(self.context_mean.shape):
            raise ValueError("V19 context width drifted")
        if tuple(action.shape) != tuple(self.action_scale.shape):
            raise ValueError("V19 action feature width drifted")
        if tuple(explicit.shape) != tuple(self.explicit_scale.shape):
            raise ValueError("V19 explicit feature width drifted")

        context_z = (context - self.context_mean) / self.context_std
        context_low = self.context_components @ context_z

        # Action blocks are scale-only, never mean-centered. Therefore a zero action stays exactly zero.
        action_z = action / self.action_scale
        action_low = self.action_components @ action_z
        explicit_z = explicit / self.explicit_scale

        context_action = torch.outer(context_low, action_low).reshape(-1)
        context_explicit = torch.outer(
            context_low,
            explicit_z[:EXPLICIT_INTERACTION_DIM],
        ).reshape(-1)
        design = torch.cat(
            (
                action_low,
                explicit_z,
                context_action,
                context_explicit,
            ),
            dim=0,
        )
        if not bool(torch.isfinite(design).all()):
            raise RuntimeError("V19 transformed advantage features contain non-finite values")
        return design


class ZeroAnchoredAdvantageRegressorV19(nn.Module):
    """No-intercept numeric advantage model; HOLD/reference is an exact zero prediction."""

    def __init__(
        self,
        *,
        preprocessor: ZeroAnchoredAdvantagePreprocessorV19,
        weight: torch.Tensor,
        target_scale_m3: float,
    ) -> None:
        super().__init__()
        if tuple(weight.reshape(-1).shape) != (preprocessor.output_dim,):
            raise ValueError("V19 advantage weight width mismatch")
        scale = float(target_scale_m3)
        if not math.isfinite(scale) or scale <= 0.0:
            raise ValueError("V19 target scale must be finite and positive")
        self.preprocessor = preprocessor
        self.register_buffer("weight", weight.reshape(-1).detach().to(torch.float32))
        self.register_buffer("target_scale_m3", torch.tensor(scale, dtype=torch.float32))

    def coordinate(self, parts: ZeroAnchoredAdvantagePartsV19) -> torch.Tensor:
        design = self.preprocessor(parts)
        return torch.dot(self.weight.to(design.device), design)

    def predict(self, parts: ZeroAnchoredAdvantagePartsV19) -> AdvantagePredictionV19:
        coordinate = self.coordinate(parts)
        bounded = torch.clamp(
            coordinate,
            min=-ADVANTAGE_COORDINATE_MAX,
            max=ADVANTAGE_COORDINATE_MAX,
        )
        advantage = torch.sinh(bounded) * self.target_scale_m3.to(coordinate.device)
        return AdvantagePredictionV19(
            coordinate=coordinate,
            advantage_m3=advantage,
            execute=coordinate < 0.0,
        )


def load_advantage_v19_checkpoint(
    checkpoint_path: str | Path,
    *,
    graph: Any,
    base_step2_path: str | Path,
    device: torch.device,
) -> tuple[
    torch.nn.Module,
    Any,
    QueryConditionedPolicyReturnAdapterV17,
    ZeroAnchoredAdvantageRegressorV19,
    dict[str, Any],
]:
    """Load the frozen Step2 + V15 rank + zero-anchored V19 advantage stack."""
    payload = torch.load(
        checkpoint_path,
        map_location="cpu",
        weights_only=False,
        mmap=True,
    )
    if (
        not isinstance(payload, dict)
        or payload.get("contract") != DIRECT_TFV_ADVANTAGE_V19_CHECKPOINT_CONTRACT
    ):
        raise ValueError("runtime requires a V19 zero-anchored Step3 checkpoint")
    if str(payload.get("base_step2_sha256", "")).lower() != sha256_file(base_step2_path).lower():
        raise ValueError("V19 checkpoint/base Step2 SHA mismatch")

    rank_model, normalization, _base = load_direct_tfv_runtime_checkpoint(
        base_step2_path,
        graph=graph,
        device=device,
    )
    for parameter in rank_model.parameters():
        parameter.requires_grad_(False)
    rank_model.eval()

    rank_state = payload.get("rank_source_state_dict")
    if not isinstance(rank_state, dict):
        raise ValueError("V19 checkpoint lacks the frozen V15 rank state")
    rank_payload = {
        "contract": LEGACY_V15_CHECKPOINT_CONTRACT,
        "context_dim": int(payload["context_dim"]),
        "candidate_dim": int(payload["candidate_dim"]),
        "query_margin_state_dict": rank_state,
    }
    rank_adapter = QueryConditionedPolicyReturnAdapterV17(
        target_scale_m3=float(rank_model.target_scale_m3.detach().cpu()),
        context_dim=int(payload["context_dim"]),
        candidate_dim=int(payload["candidate_dim"]),
    ).to(device)
    import_v15_rank_state(rank_adapter, rank_payload)
    rank_adapter.eval()

    state = payload.get("advantage_preprocessor_state")
    if not isinstance(state, dict):
        raise ValueError("V19 checkpoint lacks advantage preprocessor state")
    preprocessor = ZeroAnchoredAdvantagePreprocessorV19(
        context_mean=torch.as_tensor(state["context_mean"], dtype=torch.float32, device=device),
        context_std=torch.as_tensor(state["context_std"], dtype=torch.float32, device=device),
        context_components=torch.as_tensor(
            state["context_components"],
            dtype=torch.float32,
            device=device,
        ),
        action_scale=torch.as_tensor(state["action_scale"], dtype=torch.float32, device=device),
        action_components=torch.as_tensor(
            state["action_components"],
            dtype=torch.float32,
            device=device,
        ),
        explicit_scale=torch.as_tensor(state["explicit_scale"], dtype=torch.float32, device=device),
    ).to(device)
    regressor = ZeroAnchoredAdvantageRegressorV19(
        preprocessor=preprocessor,
        weight=torch.as_tensor(payload["advantage_weight"], dtype=torch.float32, device=device),
        target_scale_m3=float(payload["target_scale_m3"]),
    ).to(device)
    regressor.eval()
    return rank_model, normalization, rank_adapter, regressor, payload


__all__ = [
    "ACTION_COMPONENTS",
    "ADVANTAGE_COORDINATE_MAX",
    "AdvantagePredictionV19",
    "CONTEXT_COMPONENTS",
    "DIRECT_TFV_ADVANTAGE_V19_CHECKPOINT_CONTRACT",
    "DIRECT_TFV_ADVANTAGE_V19_CONTRACT",
    "DIRECT_TFV_ADVANTAGE_V19_FEATURE_CONTRACT",
    "EXPLICIT_INTERACTION_DIM",
    "LEGACY_CANDIDATE_WIDTH",
    "ZeroAnchoredAdvantagePartsV19",
    "ZeroAnchoredAdvantagePreprocessorV19",
    "ZeroAnchoredAdvantageRegressorV19",
    "build_zero_anchored_advantage_parts_v19",
    "load_advantage_v19_checkpoint",
]
