from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd

from .inp_lineage import physical_contract_sha256
from .pipeline import PipelineLedger, create_policy_lock, evidence_from_files, sha256_file


_REQUIRED = {
    "frozen_inp",
    "priority_nodes",
    "sensor_layout",
    "time_scale_config",
    "step1_model",
    "step2_model",
    "graph_schema",
    "state_schema",
    "actuator_catalog",
    "split_registry",
    "model_acceptance_contract",
    "step1_acceptance",
    "step2_acceptance",
    "gradient_acceptance",
    "candidate_ranking_acceptance",
    "safety_calibration",
    "safety_audit",
    "controller_config",
    "rainfall_forecast_config",
    "fallback_policy",
    "baseline_plan",
}

_EVIDENCE_SECTIONS = {
    "step1_acceptance": "step1",
    "step2_acceptance": "step2",
    "gradient_acceptance": "gradient",
    "candidate_ranking_acceptance": "candidate_ranking",
}


def _json(path: str | Path) -> dict[str, object]:
    payload = json.loads(Path(path).read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"JSON artifact is not an object: {path}")
    return payload


def _lines(path: str | Path) -> tuple[str, ...]:
    return tuple(
        line.strip()
        for line in Path(path).read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    )


def _normalize_thresholds(value: object) -> dict[str, dict[str, float]]:
    if not isinstance(value, dict):
        raise ValueError("threshold section must be an object")
    minimum_raw, maximum_raw = value.get("minimum", {}), value.get("maximum", {})
    if not isinstance(minimum_raw, dict) or not isinstance(maximum_raw, dict):
        raise ValueError("threshold minimum/maximum must be objects")
    minimum = {str(k): float(v) for k, v in minimum_raw.items()}
    maximum = {str(k): float(v) for k, v in maximum_raw.items()}
    if not minimum and not maximum:
        raise ValueError("every formal acceptance section must preregister at least one threshold")
    overlap = set(minimum) & set(maximum)
    if overlap:
        raise ValueError(f"metric cannot have both minimum and maximum thresholds: {sorted(overlap)}")
    return {"minimum": minimum, "maximum": maximum}


def _verify_acceptance_contract(artefacts: dict[str, str]) -> None:
    contract = _json(artefacts["model_acceptance_contract"])
    if contract.get("contract") != "MODEL_ACCEPTANCE_CONTRACT_V2":
        raise ValueError("formal lock requires MODEL_ACCEPTANCE_CONTRACT_V2")
    for evidence_name, section_name in _EVIDENCE_SECTIONS.items():
        if section_name not in contract:
            raise ValueError(f"acceptance contract lacks section: {section_name}")
        frozen = _normalize_thresholds(contract[section_name])
        evidence = _json(artefacts[evidence_name])
        if evidence.get("passed") is not True:
            raise ValueError(f"formal acceptance evidence did not pass: {evidence_name}")
        used = _normalize_thresholds(evidence.get("thresholds", {}))
        if used != frozen:
            raise ValueError(
                f"{evidence_name} used thresholds different from locked preregistration"
            )
        metrics = evidence.get("metrics")
        if not isinstance(metrics, dict):
            raise ValueError(f"{evidence_name} lacks metrics")
        missing_metrics = sorted((set(frozen["minimum"]) | set(frozen["maximum"])) - set(metrics))
        if missing_metrics:
            raise ValueError(f"{evidence_name} lacks thresholded metrics: {missing_metrics}")

    step1 = _json(artefacts["step1_acceptance"])
    step2 = _json(artefacts["step2_acceptance"])
    gradient = _json(artefacts["gradient_acceptance"])
    ranking = _json(artefacts["candidate_ranking_acceptance"])
    if str(step1.get("model_sha256", "")) != sha256_file(artefacts["step1_model"]):
        raise ValueError("Step1 acceptance model SHA differs from locked Step1 checkpoint")
    expected_step2 = sha256_file(artefacts["step2_model"])
    if str(step2.get("model_sha256", "")) != expected_step2:
        raise ValueError("Step2 acceptance model SHA differs from locked Step2 checkpoint")
    for name, evidence in (("gradient", gradient), ("candidate_ranking", ranking)):
        if str(evidence.get("step2_sha256", "")) != expected_step2:
            raise ValueError(f"{name} evidence was not generated by the locked Step2 model")


def _verify_split_registry(path: str | Path) -> None:
    frame = pd.read_csv(path)
    if not {"rainfall_group", "scientific_split"}.issubset(frame.columns):
        raise ValueError("split registry requires rainfall_group/scientific_split")
    cross = frame.groupby(frame["rainfall_group"].astype(str))["scientific_split"].nunique()
    if (cross != 1).any():
        raise ValueError("rainfall-group leakage exists in split registry")
    required = {"development", "calibration", "safety_audit", "final"}
    present = set(frame["scientific_split"].astype(str))
    if not required.issubset(present):
        raise ValueError(f"split registry missing roles: {sorted(required-present)}")
    if "development_fold" in frame.columns:
        dev = frame[frame["scientific_split"].astype(str) == "development"]
        folds = set(dev["development_fold"].astype(str))
        if folds != {"train", "validation"}:
            raise ValueError(f"development folds must be train/validation, got {sorted(folds)}")
        fold_cross = dev.groupby(dev["rainfall_group"].astype(str))["development_fold"].nunique()
        if (fold_cross != 1).any():
            raise ValueError("rainfall-group leakage exists across development folds")


def _verify_sensor_and_time_scale(artefacts: dict[str, str]) -> None:
    sensors = _lines(artefacts["sensor_layout"])
    if not sensors or len(set(sensors)) != len(sensors):
        raise ValueError("sensor layout must contain unique sensor node IDs")
    graph = np.load(artefacts["graph_schema"], allow_pickle=False)
    node_ids = set(graph["node_ids"].astype(str).tolist())
    missing = sorted(set(sensors) - node_ids)
    if missing:
        raise ValueError(f"locked sensors are absent from graph schema: {missing}")

    time_cfg = _json(artefacts["time_scale_config"])
    controller = _json(artefacts["controller_config"])
    for key in ("model_step_seconds", "control_update_seconds"):
        if key not in time_cfg or key not in controller:
            raise ValueError(f"time-scale/controller config both require {key}")
        if int(time_cfg[key]) != int(controller[key]):
            raise ValueError(f"time-scale/controller mismatch for {key}")
    model_step = int(time_cfg["model_step_seconds"])
    control_step = int(time_cfg["control_update_seconds"])
    if model_step <= 0 or control_step % model_step:
        raise ValueError("control_update_seconds must be an integer multiple of model_step_seconds")
    if "horizon_steps" in time_cfg:
        controller_section = controller.get("controller", {})
        if not isinstance(controller_section, dict):
            raise ValueError("controller_config.controller must be an object")
        if int(controller_section.get("horizon_steps", -1)) != int(time_cfg["horizon_steps"]):
            raise ValueError("controller horizon_steps differs from frozen time-scale config")

    forecast_locked = _json(artefacts["rainfall_forecast_config"])
    forecast_runtime = controller.get("forecast")
    if forecast_runtime != forecast_locked:
        raise ValueError("production controller forecast settings differ from locked forecast config")


def create_formal_policy_lock_v3(
    *, ledger_path: str | Path, artefacts_path: str | Path, output_path: str | Path
) -> dict[str, object]:
    ledger = PipelineLedger.from_json(ledger_path)
    ledger.require_ready_for("policy_lock")
    ledger.verify_integrity()
    raw = _json(artefacts_path)
    artefacts = {str(k): str(v) for k, v in raw.items()}
    missing = sorted(_REQUIRED - set(artefacts))
    if missing:
        raise ValueError(f"formal Policy Lock missing artefacts: {missing}")
    for name in sorted(_REQUIRED):
        if not Path(artefacts[name]).is_file():
            raise ValueError(f"formal Policy Lock artifact missing: {name}: {artefacts[name]}")

    priority = _lines(artefacts["priority_nodes"])
    if len(priority) != 8 or len(set(priority)) != 8:
        raise ValueError(f"formal Wuhan contract requires exactly 8 unique priority nodes, got {len(priority)}")
    _verify_split_registry(artefacts["split_registry"])
    _verify_acceptance_contract(artefacts)
    _verify_sensor_and_time_scale(artefacts)

    safety = _json(artefacts["safety_audit"])
    if safety.get("passed") is not True:
        raise ValueError("independent safety audit did not pass")
    if safety.get("rainfall_group_overlap") not in ([], None):
        raise ValueError("safety audit reports calibration/audit rainfall-group overlap")

    plan = _json(artefacts["baseline_plan"])
    strategies = [str(x) for x in plan.get("strategies", [])]
    if "proposed" not in strategies or len(strategies) < 2 or len(set(strategies)) != len(strategies):
        raise ValueError("baseline plan must contain proposed plus unique comparison strategies")

    lock = create_policy_lock(ledger=ledger, artefacts=artefacts, output_path=output_path)
    lock["formal_contract"] = "WUHAN_RTC_FORMAL_POLICY_LOCK_V2"
    lock["formal_lock_revision"] = 3
    lock["physical_network_sha256"] = physical_contract_sha256(artefacts["frozen_inp"])
    lock["priority_nodes"] = list(priority)
    lock["sensor_nodes"] = list(_lines(artefacts["sensor_layout"]))
    Path(output_path).write_text(json.dumps(lock, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    ledger.record(
        evidence_from_files(
            "policy_lock", [output_path], passed=True, notes=str(lock["policy_sha256"])
        )
    )
    ledger.to_json(ledger_path)
    return lock


def main() -> None:
    parser = argparse.ArgumentParser(description="Create consistency-checked formal Policy Lock revision 3")
    parser.add_argument("--ledger", required=True)
    parser.add_argument("--artifacts", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()
    payload = create_formal_policy_lock_v3(
        ledger_path=args.ledger, artefacts_path=args.artifacts, output_path=args.out
    )
    print(json.dumps(payload, indent=2))


if __name__ == "__main__":
    main()
