from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import numpy as np
import pandas as pd

from .inp_lineage import physical_contract_sha256
from .tfv_pipeline import TFVPipelineLedger, sha256_file


_REQUIRED = {
    "inp_preflight", "frozen_inp", "priority_nodes", "sensor_layout", "time_scale_config",
    "step1_model", "step2_model", "graph_schema", "state_schema", "actuator_catalog",
    "split_registry", "model_acceptance_contract", "step1_acceptance", "step2_acceptance",
    "gradient_acceptance", "candidate_ranking_acceptance", "controller_config",
    "rainfall_forecast_config", "fallback_policy", "baseline_plan",
}


def _json(path: str | Path) -> dict[str, object]:
    value = json.loads(Path(path).read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"JSON artifact is not an object: {path}")
    return value


def _lines(path: str | Path) -> tuple[str, ...]:
    return tuple(
        line.strip() for line in Path(path).read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    )


def _thresholds(value: object) -> dict[str, dict[str, float]]:
    if not isinstance(value, dict):
        raise ValueError("acceptance threshold section must be an object")
    result = {
        "minimum": {str(k): float(v) for k, v in value.get("minimum", {}).items()},
        "maximum": {str(k): float(v) for k, v in value.get("maximum", {}).items()},
    }
    if not result["minimum"] and not result["maximum"]:
        raise ValueError("formal threshold section is empty")
    return result


def _verify_splits(path: str | Path) -> None:
    frame = pd.read_csv(path)
    if not {"rainfall_group", "scientific_split"}.issubset(frame.columns):
        raise ValueError("split registry lacks rainfall_group/scientific_split")
    cross = frame.groupby(frame["rainfall_group"].astype(str))["scientific_split"].nunique()
    if (cross != 1).any():
        raise ValueError("rainfall-group leakage exists across scientific splits")
    required = {"development", "calibration", "safety_audit", "final"}
    present = set(frame["scientific_split"].astype(str))
    if not required.issubset(present):
        raise ValueError(f"split registry missing roles: {sorted(required-present)}")
    dev = frame[frame["scientific_split"].astype(str) == "development"]
    if "development_fold" not in dev.columns or set(dev["development_fold"].astype(str)) != {"train", "validation"}:
        raise ValueError("development split must contain rainfall-group-disjoint train/validation folds")
    if (dev.groupby(dev["rainfall_group"].astype(str))["development_fold"].nunique() != 1).any():
        raise ValueError("rainfall group crosses development train/validation folds")


def _verify_acceptance(artefacts: dict[str, str]) -> None:
    contract = _json(artefacts["model_acceptance_contract"])
    if contract.get("contract") != "MODEL_ACCEPTANCE_CONTRACT_V3_TFV_FIRST":
        raise ValueError("TFV-first lock requires MODEL_ACCEPTANCE_CONTRACT_V3_TFV_FIRST")
    mapping = {
        "step1_acceptance": "step1",
        "step2_acceptance": "step2",
        "gradient_acceptance": "gradient",
        "candidate_ranking_acceptance": "candidate_ranking",
    }
    expected_step1 = sha256_file(artefacts["step1_model"])
    expected_step2 = sha256_file(artefacts["step2_model"])
    for name, section in mapping.items():
        evidence = _json(artefacts[name])
        if evidence.get("passed") is not True:
            raise ValueError(f"formal evidence did not pass: {name}")
        frozen = _thresholds(contract.get(section))
        used = _thresholds(evidence.get("thresholds", {}))
        if frozen != used:
            raise ValueError(f"{name} thresholds differ from preregistered contract")
        metrics = evidence.get("metrics")
        if not isinstance(metrics, dict):
            raise ValueError(f"{name} lacks metrics")
        missing = (set(frozen["minimum"]) | set(frozen["maximum"])) - set(metrics)
        if missing:
            raise ValueError(f"{name} missing thresholded metrics: {sorted(missing)}")
    step1 = _json(artefacts["step1_acceptance"])
    step2 = _json(artefacts["step2_acceptance"])
    if str(step1.get("model_sha256", "")) != expected_step1:
        raise ValueError("Step1 acceptance was not generated by locked Step1 model")
    if str(step2.get("model_sha256", "")) != expected_step2:
        raise ValueError("Step2 acceptance was not generated by locked Step2 model")
    for name in ("gradient_acceptance", "candidate_ranking_acceptance"):
        ev = _json(artefacts[name])
        if str(ev.get("step2_sha256", "")) != expected_step2:
            raise ValueError(f"{name} was not generated by locked Step2 model")


def create_formal_policy_lock_v5(
    *, ledger_path: str | Path, artefacts_path: str | Path, output_path: str | Path
) -> dict[str, object]:
    ledger = TFVPipelineLedger.from_json(ledger_path)
    ledger.require_ready_for_lock()
    raw = _json(artefacts_path)
    artefacts = {str(k): str(v) for k, v in raw.items()}
    missing = sorted(_REQUIRED - set(artefacts))
    if missing:
        raise ValueError(f"TFV-first Policy Lock missing artefacts: {missing}")
    for name, path in artefacts.items():
        if not Path(path).is_file():
            raise ValueError(f"Policy Lock artifact missing: {name}: {path}")

    preflight = _json(artefacts["inp_preflight"])
    if preflight.get("contract") != "LARGE_SWMM_INP_PREFLIGHT_V2":
        raise ValueError("locked INP was not audited with large-network preflight V2")
    priority = _lines(artefacts["priority_nodes"])
    sensors = _lines(artefacts["sensor_layout"])
    if len(priority) != 8 or len(set(priority)) != 8:
        raise ValueError("Formal Wuhan reporting requires exactly eight verified observed-site node mappings")
    graph = np.load(artefacts["graph_schema"], allow_pickle=False)
    node_ids = set(graph["node_ids"].astype(str).tolist())
    missing_nodes = sorted((set(priority) | set(sensors)) - node_ids)
    if missing_nodes:
        raise ValueError(f"priority/sensor mapping is incompatible with frozen graph: {missing_nodes}")
    if set(preflight.get("missing_priority_nodes", [])):
        raise ValueError("INP preflight reports unresolved priority nodes")

    _verify_splits(artefacts["split_registry"])
    _verify_acceptance(artefacts)
    controller = _json(artefacts["controller_config"])
    if controller.get("contract") != "PRODUCTION_CONTROLLER_CONFIG_V4_TFV_FIRST":
        raise ValueError("TFV-first lock requires controller config V4")
    if controller.get("exact_global_peak") is not False:
        raise ValueError("Formal main run must use exact_global_peak=false and replay peak afterward")
    if "flood_budget_m3" in controller or "depth_budget_m" in controller:
        raise ValueError("PFV/depth hard budgets are forbidden by the TFV-first scientific contract")
    objective = controller.get("objective")
    if not isinstance(objective, dict) or objective.get("priority_role") != "soft lexicographic secondary preference within TFV near-optimal set":
        raise ValueError("controller does not declare the frozen soft-priority TFV-first objective")
    time_cfg = _json(artefacts["time_scale_config"])
    for key in ("model_step_seconds", "control_update_seconds"):
        if int(controller[key]) != int(time_cfg[key]):
            raise ValueError(f"controller/time-scale mismatch: {key}")
    if int(controller["control_update_seconds"]) % int(controller["model_step_seconds"]):
        raise ValueError("control update is not an integer multiple of model step")

    plan = _json(artefacts["baseline_plan"])
    strategies = [str(x) for x in plan.get("strategies", [])]
    required_strategies = {"proposed", "no_control", "internal_rtc"}
    if not required_strategies.issubset(strategies):
        raise ValueError("baseline plan must explicitly separate proposed/no_control/internal_rtc")
    if "native_rules" in strategies or "passive_no_rtc" in strategies:
        raise ValueError("legacy ambiguous baseline IDs are forbidden in new Formal evidence")

    # Optional priority calibration can be locked for uncertainty-aware soft ranking, but it
    # is not a safety veto and no independent PFV-pass gate is required.
    hashes = {name: sha256_file(path) for name, path in sorted(artefacts.items())}
    canonical = json.dumps(hashes, sort_keys=True, separators=(",", ":"))
    policy_sha = hashlib.sha256(canonical.encode("utf-8")).hexdigest()
    payload: dict[str, object] = {
        "contract": "WUHAN_RTC_TFV_FIRST_POLICY_LOCK_V2",
        "policy_sha256": policy_sha,
        "physical_network_sha256": physical_contract_sha256(artefacts["frozen_inp"]),
        "objective_contract": "TFV_PRIMARY__PRIORITY_PFV_SOFT_SECONDARY_V1",
        "priority_is_hard_constraint": False,
        "priority_nodes": list(priority),
        "sensor_nodes": list(sensors),
        "artefacts": artefacts,
        "sha256": hashes,
    }
    out = Path(output_path); out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return payload


def main() -> None:
    parser = argparse.ArgumentParser(description="Create TFV-first Policy Lock revision 5")
    parser.add_argument("--ledger", required=True)
    parser.add_argument("--artifacts", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()
    payload = create_formal_policy_lock_v5(
        ledger_path=args.ledger, artefacts_path=args.artifacts, output_path=args.out
    )
    print(json.dumps(payload, indent=2))


if __name__ == "__main__":
    main()
