from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import numpy as np
import pandas as pd

from .causal_timing import timing_from_controller_config
from .code_contract import rtc_source_tree_sha256
from .project7_contract import (
    EFFECTIVE_WARMUP_MINUTES,
    MAX_SETTING_DELTA_PER_UPDATE,
    PREDICTION_HORIZON_MINUTES,
    validate_project7_runtime_config,
)
from .runtime_controller_guard import CONTINUITY_GUARD_CONTRACT


def _sha(path: str | Path) -> str:
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def _json(path: str | Path) -> dict[str, object]:
    value = json.loads(Path(path).read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"JSON must be an object: {path}")
    return value


def _decisions(
    metadata_path: str | Path,
) -> tuple[dict[str, object], list[dict[str, object]]]:
    meta_path = Path(metadata_path)
    meta = _json(meta_path)
    decision_name = meta.get("decision_file")
    if not decision_name:
        raise ValueError(f"closed-loop metadata lacks decision_file: {metadata_path}")
    decision_path = meta_path.parent / str(decision_name)
    rows: list[dict[str, object]] = []
    for raw in decision_path.read_text(encoding="utf-8").splitlines():
        if raw.strip():
            item = json.loads(raw)
            if not isinstance(item, dict):
                raise ValueError("decision log row must be a JSON object")
            rows.append(item)
    return meta, rows


def build_runtime_acceptance(
    *,
    run_index_path: str | Path,
    controller_config_path: str | Path,
) -> dict[str, object]:
    config = _json(controller_config_path)
    project7 = validate_project7_runtime_config(config)
    timing = timing_from_controller_config(config)
    timing.validate(require_full_history_before_first_control=True)
    if timing.horizon_seconds != PREDICTION_HORIZON_MINUTES * 60:
        raise ValueError("runtime acceptance requires the frozen 360-minute horizon")
    controller_section = config.get("controller")
    if not isinstance(controller_section, dict):
        raise ValueError("controller config lacks controller section")
    raw_budget = controller_section.get("decision_runtime_budget_seconds")
    if raw_budget is None:
        raise ValueError(
            "Formal runtime acceptance requires decision_runtime_budget_seconds"
        )
    budget = float(raw_budget)
    if not 0 < budget < timing.control_update_seconds:
        raise ValueError(
            "decision runtime budget must be positive and smaller than control interval"
        )
    max_delta = float(controller_section["max_setting_delta_per_update"])
    if abs(max_delta - MAX_SETTING_DELTA_PER_UPDATE) > 1e-12:
        raise ValueError("runtime acceptance requires the frozen 0.5 setting delta")

    index = pd.read_csv(run_index_path)
    required = {"strategy", "metadata_path"}
    missing = sorted(required - set(index.columns))
    if missing:
        raise ValueError(f"development run index missing columns: {missing}")
    proposed = index[index["strategy"].astype(str) == "proposed"].copy()
    if proposed.empty:
        raise ValueError("development run index contains no Proposed runs")

    current_code_sha = rtc_source_tree_sha256()
    config_sha = _sha(controller_config_path)
    runtimes: list[float] = []
    source_counts: dict[str, int] = {}
    grid_violations = 0
    first_decision_violations = 0
    missing_runtime_diagnostics = 0
    continuity_violations = 0
    continuity_missing = 0
    horizon_path_violations = 0
    decisions_total = 0
    event_rows: list[dict[str, object]] = []
    start = timing.control_start_seconds
    update = timing.control_update_seconds

    for _, item in proposed.iterrows():
        meta, rows = _decisions(str(item["metadata_path"]))
        if meta.get("rtc_source_tree_sha256") != current_code_sha:
            raise ValueError(
                "Proposed development run was generated by a different RTC source tree"
            )
        if meta.get("strategy") != "proposed":
            raise ValueError("runtime acceptance input is not stamped as Proposed")
        if str(meta.get("controller_config_sha256", "")) != config_sha:
            raise ValueError(
                "development run controller config differs from runtime-acceptance config"
            )
        if not meta.get("step1_model_sha256") or not meta.get("step2_model_sha256"):
            raise ValueError("Proposed run lacks locked Step1/Step2 model lineage")
        event_clock = meta.get("prepared_event_clock")
        if not isinstance(event_clock, dict):
            raise ValueError("Proposed run lacks prepared_event_clock evidence")
        if abs(float(event_clock.get("effective_warmup_minutes", -1.0)) - EFFECTIVE_WARMUP_MINUTES) > 1e-6:
            raise ValueError("Proposed run was not executed on effective 120-minute warm-up event")
        if not isinstance(meta.get("project7_runtime_contract"), dict):
            raise ValueError("Proposed run lacks Project7 runtime-contract evidence")
        if int(meta.get("control_update_seconds", -1)) != update:
            raise ValueError(
                "development run control_update differs from frozen controller config"
            )
        if int(meta.get("observation_update_seconds", -1)) != timing.model_step_seconds:
            raise ValueError(
                "development run observation cadence differs from model step"
            )
        if int(meta.get("record_stride_seconds", -1)) != timing.model_step_seconds:
            raise ValueError(
                "development run record cadence differs from online model step"
            )
        if int(meta.get("control_start_minutes", -1)) * 60 != start:
            raise ValueError(
                "development run control start differs from frozen controller config"
            )
        if int(meta.get("initial_observation_elapsed_seconds", -1)) != 0:
            raise ValueError("development run lacks the causal t=0 initial observation")
        if not rows:
            raise ValueError(
                f"Proposed development run has no decisions: {item['metadata_path']}"
            )
        elapsed = [int(row["elapsed_seconds"]) for row in rows]
        if elapsed[0] != start:
            first_decision_violations += 1
        event_grid = sum(
            1 for t in elapsed if t < start or (t - start) % update != 0
        )
        grid_violations += event_grid
        event_runtime: list[float] = []
        event_continuity_violations = 0
        event_horizon_violations = 0
        for row in rows:
            source = str(row.get("source", ""))
            source_counts[source] = source_counts.get(source, 0) + 1
            diagnostics = row.get("diagnostics")
            if not isinstance(diagnostics, dict):
                missing_runtime_diagnostics += 1
                continuity_missing += 1
                continue

            if diagnostics.get("continuity_guard_contract") != CONTINUITY_GUARD_CONTRACT or diagnostics.get("continuity_guard_passed") is not True:
                continuity_missing += 1
            else:
                current_delta = float(diagnostics.get("command_delta_from_current_max", np.inf))
                previous_delta = float(
                    diagnostics.get("command_delta_from_previous_target_max", np.inf)
                )
                if (
                    not np.isfinite(current_delta)
                    or not np.isfinite(previous_delta)
                    or current_delta > max_delta + 1e-8
                    or previous_delta > max_delta + 1e-8
                ):
                    continuity_violations += 1
                    event_continuity_violations += 1

            planned_delta = diagnostics.get("planned_sequence_max_step_delta")
            if source == "MPC":
                if planned_delta is None or not np.isfinite(float(planned_delta)):
                    horizon_path_violations += 1
                    event_horizon_violations += 1
                elif float(planned_delta) > max_delta + 1e-8:
                    horizon_path_violations += 1
                    event_horizon_violations += 1

            if "decision_runtime_seconds" not in diagnostics:
                if source not in {"FALLBACK_HISTORY_WARMUP", "FALLBACK_READBACK"}:
                    missing_runtime_diagnostics += 1
                continue
            runtime = float(diagnostics["decision_runtime_seconds"])
            if not np.isfinite(runtime) or runtime < 0:
                raise ValueError(
                    "invalid decision_runtime_seconds in development log"
                )
            runtimes.append(runtime)
            event_runtime.append(runtime)
        decisions_total += len(rows)
        event_rows.append(
            {
                "event_id": str(item.get("event_id", "")),
                "rainfall_group": str(item.get("rainfall_group", "")),
                "decisions": len(rows),
                "grid_violations": event_grid,
                "continuity_violations": event_continuity_violations,
                "horizon_path_violations": event_horizon_violations,
                "max_runtime_seconds": (
                    max(event_runtime) if event_runtime else np.nan
                ),
            }
        )

    fatal_sources = {
        "FALLBACK_HISTORY_WARMUP",
        "FALLBACK_READBACK",
        "FALLBACK_RUNTIME_ERROR",
        "FALLBACK_COMPUTE_DEADLINE",
    }
    fatal_count = sum(source_counts.get(name, 0) for name in fatal_sources)
    max_runtime = float(max(runtimes)) if runtimes else np.inf
    p95 = float(np.quantile(runtimes, 0.95)) if runtimes else np.inf
    p99 = float(np.quantile(runtimes, 0.99)) if runtimes else np.inf
    passed = bool(
        grid_violations == 0
        and first_decision_violations == 0
        and missing_runtime_diagnostics == 0
        and continuity_missing == 0
        and continuity_violations == 0
        and horizon_path_violations == 0
        and fatal_count == 0
        and max_runtime <= budget
    )
    return {
        "contract": "DEVELOPMENT_REALTIME_EXECUTION_ACCEPTANCE_V2_TEMPORAL_CONTINUITY",
        "passed": passed,
        "rtc_source_tree_sha256": current_code_sha,
        "controller_config_sha256": config_sha,
        "run_index_sha256": _sha(run_index_path),
        "project7_runtime_contract": project7,
        "timing": timing.as_dict(),
        "decision_runtime_budget_seconds": budget,
        "metrics": {
            "proposed_events": int(len(proposed)),
            "decisions": int(decisions_total),
            "decision_runtime_p95_seconds": p95,
            "decision_runtime_p99_seconds": p99,
            "decision_runtime_max_seconds": max_runtime,
            "control_grid_violations": int(grid_violations),
            "first_decision_violations": int(first_decision_violations),
            "missing_runtime_diagnostics": int(missing_runtime_diagnostics),
            "continuity_evidence_missing": int(continuity_missing),
            "cross_decision_continuity_violations": int(continuity_violations),
            "planned_horizon_continuity_violations": int(horizon_path_violations),
            "fatal_runtime_fallbacks": int(fatal_count),
            "optimizer_candidate_fallbacks": int(
                source_counts.get("FALLBACK", 0)
            ),
        },
        "decision_source_counts": source_counts,
        "fatal_sources": sorted(fatal_sources),
        "events": event_rows,
        "interpretation": (
            "Policy Lock requires real current-code Proposed decisions on the frozen event clock: "
            "first control at elapsed 60 min, 360-min horizon, complete 13-frame history, "
            "effective 120-min event warm-up, continuous setting evolution across the full MPC "
            "path and across rolling decisions, successful write/readback, no runtime/deadline "
            "fallback, and wall-clock compute within budget."
        ),
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Fail-closed real-time execution and temporal-continuity gate"
    )
    parser.add_argument("--run-index", required=True)
    parser.add_argument("--config", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()
    payload = build_runtime_acceptance(
        run_index_path=args.run_index,
        controller_config_path=args.config,
    )
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(json.dumps(payload, indent=2))
    if payload["passed"] is not True:
        raise SystemExit(2)


if __name__ == "__main__":
    main()
