"""Causal Step1-state store and cache adapter for Project7 V127 Step2.

Historical D2/D3/D4 branch tensors correctly retain authoritative SWMM checkpoint state
and realised future rainfall because those branches were generated by SWMM.  Neither is
an admissible online Step2 input.  V127 therefore composes two explicit adapters:

* V123 causal-rainfall cache replaces future realised rain with the runtime-equivalent
  forecast;
* this V127 adapter replaces the authoritative checkpoint ``initial_state`` with the
  frozen Step1 reconstruction made from the same sparse causal sensor history used
  online.

Future SWMM states/flows/flood volumes remain untouched supervision labels.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import hashlib
from typing import Any, Sequence

import numpy as np
import torch

from .step2_causal_rainfall_v123 import CausalForecastStoreV123
from .step2_train_response_v60 import InputNormalizationV60, V60GroupBatch

V127_CAUSAL_STATE_CONTRACT = "PROJECT7_V127_CAUSAL_STEP1_STATE_STORE_V1"


def _sha256_array(value: np.ndarray) -> str:
    array = np.ascontiguousarray(value)
    return hashlib.sha256(array.view(np.uint8)).hexdigest()


def _channel_stats(values: Sequence[np.ndarray], channels: int) -> tuple[np.ndarray, np.ndarray]:
    total = np.zeros(channels, dtype=np.float64)
    square = np.zeros(channels, dtype=np.float64)
    count = 0
    for value in values:
        x = np.asarray(value, dtype=np.float64).reshape(-1, channels)
        total += x.sum(axis=0)
        square += np.square(x).sum(axis=0)
        count += int(x.shape[0])
    if count <= 0:
        raise ValueError("V127 cannot derive normalization from an empty source")
    mean = total / count
    std = np.sqrt(np.maximum(square / count - mean * mean, 1.0e-12))
    return mean.astype(np.float32), std.astype(np.float32)


@dataclass(frozen=True)
class CausalStateStoreV127:
    event_ids: tuple[str, ...]
    checkpoint_ids: tuple[str, ...]
    elapsed_seconds: np.ndarray
    state_si: np.ndarray
    current_setting: np.ndarray
    state_sha256: tuple[str, ...]
    step1_sha256: str
    sensor_sha256: str
    graph_sha256: str
    contract: str = V127_CAUSAL_STATE_CONTRACT

    def validate(self) -> None:
        count = len(self.event_ids)
        if self.contract != V127_CAUSAL_STATE_CONTRACT or count <= 0:
            raise ValueError("invalid/empty V127 causal Step1-state store")
        if len(self.checkpoint_ids) != count or self.elapsed_seconds.shape != (count,):
            raise ValueError("V127 causal-state identity arrays are misaligned")
        if self.state_si.ndim != 3 or self.state_si.shape[0] != count:
            raise ValueError("V127 causal state must be [checkpoint,node,state]")
        if self.current_setting.ndim != 2 or self.current_setting.shape[0] != count:
            raise ValueError("V127 current setting must be [checkpoint,actuator]")
        if not np.isfinite(self.state_si).all() or not np.isfinite(self.current_setting).all():
            raise ValueError("V127 causal state store contains non-finite values")
        if np.any((self.current_setting < -1e-7) | (self.current_setting > 1.0 + 1e-7)):
            raise ValueError("V127 causal current setting is outside [0,1]")
        keys = list(zip(self.event_ids, self.checkpoint_ids, self.elapsed_seconds.tolist(), strict=True))
        if len(set(keys)) != count:
            raise ValueError("V127 causal state store duplicates event/checkpoint identities")
        if len(self.state_sha256) != count:
            raise ValueError("V127 causal state store lacks per-state hashes")
        for i, expected in enumerate(self.state_sha256):
            if _sha256_array(self.state_si[i]) != str(expected):
                raise ValueError("V127 causal Step1 state content hash mismatch")
        for value in (self.step1_sha256, self.sensor_sha256, self.graph_sha256):
            if len(str(value)) != 64:
                raise ValueError("V127 causal state store lacks canonical frozen lineage SHA")

    def index(self) -> dict[tuple[str, str], int]:
        self.validate()
        result: dict[tuple[str, str], int] = {}
        for i, (event, checkpoint) in enumerate(zip(self.event_ids, self.checkpoint_ids, strict=True)):
            key = (str(event), str(checkpoint))
            if key in result:
                raise ValueError(f"V127 causal state duplicates event/checkpoint key: {key}")
            result[key] = i
        return result

    def state_for(self, entry: Any) -> np.ndarray:
        key = (str(entry.event_id), str(entry.checkpoint_id))
        index = self.index().get(key)
        if index is None:
            raise KeyError(f"V127 causal state store has no {key}")
        return np.asarray(self.state_si[index], dtype=np.float32)

    def current_setting_for(self, entry: Any) -> np.ndarray:
        key = (str(entry.event_id), str(entry.checkpoint_id))
        index = self.index().get(key)
        if index is None:
            raise KeyError(f"V127 causal state store has no {key}")
        return np.asarray(self.current_setting[index], dtype=np.float32)


def load_causal_state_store_v127(path: str | Path) -> CausalStateStoreV127:
    with np.load(path, allow_pickle=False) as raw:
        required = {
            "contract", "event_ids", "checkpoint_ids", "elapsed_seconds", "state_si",
            "current_setting", "state_sha256", "step1_sha256", "sensor_sha256", "graph_sha256",
        }
        missing = sorted(required - set(raw.files))
        if missing:
            raise ValueError(f"V127 causal state store missing: {missing}")
        result = CausalStateStoreV127(
            event_ids=tuple(raw["event_ids"].astype(str).tolist()),
            checkpoint_ids=tuple(raw["checkpoint_ids"].astype(str).tolist()),
            elapsed_seconds=raw["elapsed_seconds"].astype(np.int64),
            state_si=raw["state_si"].astype(np.float32),
            current_setting=raw["current_setting"].astype(np.float32),
            state_sha256=tuple(raw["state_sha256"].astype(str).tolist()),
            step1_sha256=str(raw["step1_sha256"].item()),
            sensor_sha256=str(raw["sensor_sha256"].item()),
            graph_sha256=str(raw["graph_sha256"].item()),
            contract=str(raw["contract"].item()),
        )
    result.validate()
    return result


def derive_v127_input_normalization(
    *,
    base_cache: Any,
    causal_rainfall: CausalForecastStoreV123,
    causal_state: CausalStateStoreV127,
    fit_names: Sequence[str],
) -> InputNormalizationV60:
    """Fit normalization exclusively from causal TrainFit inputs.

    State statistics come from frozen Step1 estimates, rainfall statistics from the
    runtime-equivalent causal forecast, and current actuator-flow statistics from the
    branch checkpoint.  No future SWMM state or realised future rain enters the input
    normalization.
    """
    names = tuple(str(name) for name in fit_names)
    if not names or len(set(names)) != len(names):
        raise ValueError("V127 normalization requires unique non-empty TrainFit groups")
    causal_state.validate()
    causal_rainfall.validate()
    rain_index = causal_rainfall.index()
    missing_rain = [name for name in names if name not in rain_index]
    if missing_rain:
        raise ValueError(f"V127 causal rainfall misses TrainFit groups: {missing_rain[:20]}")
    entries = [base_cache.entry(name) for name in names]
    state_values = [causal_state.state_for(entry) for entry in entries]
    first = entries[0].arrays
    state_dim = int(state_values[0].shape[-1])
    rain_dim = int(causal_rainfall.forecast_mmhr.shape[-1])
    flow_dim = int(np.asarray(first["previous_actuator_flow"]).shape[-1])
    sm, ss = _channel_stats(state_values, state_dim)
    rm, rs = _channel_stats(
        [np.asarray(causal_rainfall.forecast_mmhr[rain_index[name]], dtype=np.float32) for name in names],
        rain_dim,
    )
    fm, fs = _channel_stats(
        [
            np.asarray(entry.arrays["previous_actuator_flow"][entry.reference_index], dtype=np.float32)
            for entry in entries
        ],
        flow_dim,
    )
    return InputNormalizationV60(sm, ss, rm, rs, fm, fs)


class CausalStep1StateCacheV127:
    """Read-only wrapper that makes any causal-rainfall cache online-state equivalent."""

    def __init__(self, base: Any, store: CausalStateStoreV127) -> None:
        store.validate()
        self.base = base
        self.store = store
        missing: list[str] = []
        for name in base.names():
            try:
                _ = store.state_for(base.entry(name))
            except KeyError:
                missing.append(name)
        if missing:
            raise ValueError(f"V127 causal Step1 store misses cache groups: {missing[:20]}")

    @property
    def manifest_path(self):
        return getattr(self.base, "manifest_path", "V127_CAUSAL_STATE_WRAPPER")

    def names(self, source: str | None = None) -> list[str]:
        return self.base.names(source)

    def entry(self, name: str):
        return self.base.entry(name)

    def targeted_d3_names(self) -> list[str]:
        return self.base.targeted_d3_names()

    def legacy_d3_names(self) -> list[str]:
        return self.base.legacy_d3_names()

    def batch(
        self,
        name: str,
        normalization: InputNormalizationV60,
        device: torch.device | str,
    ) -> V60GroupBatch:
        original = self.base.batch(name, normalization, device)
        raw = self.store.state_for(self.entry(name))
        if raw.shape != tuple(original.initial_state.shape[1:]):
            raise ValueError(f"{name}: V127 causal Step1 state shape mismatch")
        normalized = (raw - normalization.state_mean) / np.maximum(
            normalization.state_std, 1.0e-6
        )
        initial = torch.as_tensor(
            normalized,
            dtype=original.initial_state.dtype,
            device=torch.device(device),
        )[None]
        return V60GroupBatch(
            source_kind=original.source_kind,
            group_name=original.group_name,
            initial_state=initial,
            rainfall=original.rainfall,
            reference_settings=original.reference_settings,
            candidate_settings=original.candidate_settings,
            previous_actuator_flow=original.previous_actuator_flow,
            elapsed_seconds=original.elapsed_seconds,
            true_reference_states=original.true_reference_states,
            true_candidate_states=original.true_candidate_states,
            true_reference_flows=original.true_reference_flows,
            true_candidate_flows=original.true_candidate_flows,
            true_delta_tfv_m3=original.true_delta_tfv_m3,
        )


__all__ = [
    "CausalStateStoreV127",
    "CausalStep1StateCacheV127",
    "V127_CAUSAL_STATE_CONTRACT",
    "derive_v127_input_normalization",
    "load_causal_state_store_v127",
]
