"""Development V14: policy-return-ranked first-action portfolio.

V13 uses the receding-policy-return critic only as an accept/reject gate on the single V12 target.
That protects against some false-beneficial actions but cannot recover when the V12 open-loop
direction or magnitude is not the best executable first move.  V14 keeps the same causal state,
rainfall scenarios, TFV-only objective and q95 engineering support, but asks the policy-return critic
to rank a small deterministic portfolio of supported first targets.

The portfolio contains scaled versions of the learned V12 direction plus a type-aware hydraulic
pressure proposal and a learned/physical blend.  It never contains Auto-RBC, EFD, All-open or any
other baseline command.  The selected target is the candidate with the smallest calibrated
policy-return upper bound; HOLD is executed when every candidate has non-negative upper bound.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Mapping

import torch

from .direct_tfv_policy_return import (
    DIRECT_TFV_POLICY_RETURN_ADMISSION_CONTRACT,
    policy_return_margin_m3,
)
from .direct_tfv_policy_return_portfolio import (
    DIRECT_TFV_POLICY_RETURN_PORTFOLIO_CONTRACT,
    build_policy_return_candidate_portfolio,
)
from .step3_tfv_value_mpc_v11 import DirectTFVMPCResultV11, DirectTFVPolicyReturnMPCV11


DIRECT_TFV_POLICY_RETURN_PORTFOLIO_STEP3_CONTRACT = (
    "PROJECT7_DIRECT_TFV_109ACT_RECEDING_MPC_V12_POLICY_RETURN_PORTFOLIO"
)


@dataclass(frozen=True)
class DirectTFVMPCResultV12(DirectTFVMPCResultV11):
    policy_return_portfolio_contract: str = DIRECT_TFV_POLICY_RETURN_PORTFOLIO_CONTRACT
    policy_return_portfolio_candidate_count: int = 0
    policy_return_portfolio_selected_source: str = "HOLD"
    policy_return_portfolio_sources: tuple[str, ...] = ()
    policy_return_portfolio_scores_m3: tuple[float, ...] = ()
    policy_return_portfolio_upper_bounds_m3: tuple[float, ...] = ()


class DirectTFVPolicyReturnPortfolioMPCV12(DirectTFVPolicyReturnMPCV11):
    """Rank supported causal first-target alternatives by receding-policy TFV return."""

    policy_mode = "direct_tfv_all109_receding_mpc_v12_policy_return_portfolio"
    policy_mode_contract = DIRECT_TFV_POLICY_RETURN_PORTFOLIO_STEP3_CONTRACT

    def __init__(self, *, policy_return_admission: Mapping[str, Any], **kwargs: Any) -> None:
        admission = dict(policy_return_admission)
        if str(admission.get("contract", "")) != DIRECT_TFV_POLICY_RETURN_ADMISSION_CONTRACT:
            raise ValueError("V14 portfolio requires a policy-return admission artifact")
        if str(admission.get("candidate_portfolio_contract", "")) != DIRECT_TFV_POLICY_RETURN_PORTFOLIO_CONTRACT:
            raise ValueError(
                "V14 portfolio requires calibration records generated by the same candidate portfolio"
            )
        if int(admission.get("multi_candidate_query_set_count", 0)) <= 0:
            raise ValueError("V14 portfolio requires multi-candidate same-prefix calibration evidence")
        super().__init__(policy_return_admission=admission, **kwargs)

    def _supported_portfolio_target(
        self, target: torch.Tensor, active_target: torch.Tensor
    ) -> tuple[torch.Tensor, torch.Tensor, int]:
        sequence = target.reshape(1, 109).expand(
            int(self.design.prediction_horizon_steps), -1
        ).clone()
        if hasattr(self, "_contract_to_joint_sequence_support"):
            sequence = self._contract_to_joint_sequence_support(sequence, active_target)
        supported_target = sequence[0].detach()
        changed = int(
            torch.count_nonzero(torch.abs(supported_target - active_target) > 1.0e-7).item()
        )
        return supported_target, sequence.detach(), changed

    def optimize(self, **kwargs: Any) -> DirectTFVMPCResultV12:
        # Retain the full V12/V13 machinery as one learned direction generator.  Unlike V13, do not
        # stop after its accept/reject result: expose its refined target to a same-state portfolio.
        base = super().optimize(**kwargs)
        active_target = kwargs.get("active_target")
        if not isinstance(active_target, torch.Tensor) or tuple(active_target.shape) != (109,):
            raise ValueError("V14 portfolio requires a 109-dimensional active target")

        v12_sequence = getattr(base, "optimized_candidate_settings", None)
        v12_target = None
        if isinstance(v12_sequence, torch.Tensor) and tuple(v12_sequence.shape) == (
            int(self.design.prediction_horizon_steps),
            109,
        ):
            v12_target = v12_sequence[0].detach()

        portfolio = build_policy_return_candidate_portfolio(
            current_state=kwargs["current_state"],
            rainfall_scenarios=kwargs["rainfall"],
            active_target=active_target,
            v12_target=v12_target,
            graph=self.graph,
            first_radius=self.first_radius,
            max_changed_facilities=int(self.active_support_ceiling()),
            max_delta_per_update=float(self.design.max_setting_delta_per_update),
        )
        if not portfolio:
            values = dict(vars(base))
            values.update(
                {
                    "settings": self._hold_sequence(active_target).detach(),
                    "predicted_delta_tfv_m3": 0.0,
                    "selected_source": "LATCH_PREVIOUS_TARGET_EMPTY_POLICY_RETURN_PORTFOLIO",
                    "admission_margin_m3": 0.0,
                    "admission_upper_bound_m3": 0.0,
                    "admission_passed": False,
                    "policy_mode": self.policy_mode,
                    "policy_mode_contract": self.policy_mode_contract,
                    "policy_return_predicted_delta_tfv_m3": 0.0,
                    "policy_return_margin_m3": 0.0,
                    "policy_return_upper_bound_m3": 0.0,
                    "policy_return_admission_passed": False,
                    "policy_return_portfolio_candidate_count": 0,
                    "policy_return_portfolio_selected_source": "HOLD",
                    "policy_return_portfolio_sources": (),
                    "policy_return_portfolio_scores_m3": (),
                    "policy_return_portfolio_upper_bounds_m3": (),
                }
            )
            return DirectTFVMPCResultV12(**values)

        evaluated: list[tuple[str, torch.Tensor, torch.Tensor, int, float, float, float]] = []
        seen: set[bytes] = set()
        for candidate in portfolio:
            target, sequence, changed = self._supported_portfolio_target(
                candidate.target, active_target
            )
            if changed <= 0:
                continue
            key = target.detach().cpu().to(torch.float32).contiguous().numpy().tobytes()
            if key in seen:
                continue
            seen.add(key)
            score_t = self._score_policy_return_target(
                current_state=kwargs["current_state"],
                rainfall=kwargs["rainfall"],
                previous_actuator_flow=kwargs["previous_actuator_flow"],
                active_target=active_target,
                candidate_target=target,
            )
            score = float(score_t.detach().cpu())
            margin = float(policy_return_margin_m3(self.policy_return_admission, changed))
            upper = float(score + margin)
            evaluated.append(
                (candidate.source, target, sequence, changed, score, margin, upper)
            )

        if not evaluated:
            values = dict(vars(base))
            values.update(
                {
                    "settings": self._hold_sequence(active_target).detach(),
                    "predicted_delta_tfv_m3": 0.0,
                    "selected_source": "LATCH_PREVIOUS_TARGET_NO_SUPPORTED_PORTFOLIO_CHANGE",
                    "admission_margin_m3": 0.0,
                    "admission_upper_bound_m3": 0.0,
                    "admission_passed": False,
                    "policy_mode": self.policy_mode,
                    "policy_mode_contract": self.policy_mode_contract,
                    "policy_return_predicted_delta_tfv_m3": 0.0,
                    "policy_return_margin_m3": 0.0,
                    "policy_return_upper_bound_m3": 0.0,
                    "policy_return_admission_passed": False,
                    "policy_return_portfolio_candidate_count": 0,
                    "policy_return_portfolio_selected_source": "HOLD",
                    "policy_return_portfolio_sources": (),
                    "policy_return_portfolio_scores_m3": (),
                    "policy_return_portfolio_upper_bounds_m3": (),
                }
            )
            return DirectTFVMPCResultV12(**values)

        selected = min(evaluated, key=lambda row: (row[6], row[4], row[0]))
        source, target, sequence, changed, score, margin, upper = selected
        passed = bool(upper < 0.0)
        executed = sequence if passed else self._hold_sequence(active_target).detach()
        values = dict(vars(base))
        values.update(
            {
                "settings": executed,
                "optimized_candidate_settings": sequence,
                "predicted_delta_tfv_m3": float(score) if passed else 0.0,
                "raw_optimized_predicted_delta_tfv_m3": float(score),
                "selected_source": (
                    f"DIRECT_TFV_POLICY_RETURN_PORTFOLIO::{source}"
                    if passed
                    else "LATCH_PREVIOUS_TARGET_PORTFOLIO_UPPER_BOUND_NONNEGATIVE"
                ),
                "admission_margin_m3": float(margin),
                "admission_upper_bound_m3": float(upper),
                "admission_margin_kind": "receding_policy_return_portfolio_normalized",
                "admission_passed": passed,
                "first_move_changed_facility_count": int(changed) if passed else 0,
                "refined_first_move_predicted_delta_tfv_m3": float(score),
                "refined_first_move_margin_m3": float(margin),
                "refined_first_move_upper_bound_m3": float(upper),
                "refined_first_move_admission_passed": passed,
                "policy_mode": self.policy_mode,
                "policy_mode_contract": self.policy_mode_contract,
                "policy_return_predicted_delta_tfv_m3": float(score),
                "policy_return_margin_m3": float(margin),
                "policy_return_upper_bound_m3": float(upper),
                "policy_return_admission_passed": passed,
                "policy_return_portfolio_candidate_count": len(evaluated),
                "policy_return_portfolio_selected_source": source if passed else "HOLD",
                "policy_return_portfolio_sources": tuple(row[0] for row in evaluated),
                "policy_return_portfolio_scores_m3": tuple(float(row[4]) for row in evaluated),
                "policy_return_portfolio_upper_bounds_m3": tuple(float(row[6]) for row in evaluated),
            }
        )
        return DirectTFVMPCResultV12(**values)


__all__ = [
    "DIRECT_TFV_POLICY_RETURN_PORTFOLIO_STEP3_CONTRACT",
    "DirectTFVMPCResultV12",
    "DirectTFVPolicyReturnPortfolioMPCV12",
]
