"""Strict managed-flow-only hydraulic isolation for Project7 V128 Development.

The normal surrogate is allowed to use the requested actuator setting because setting is a causal
online input.  The *oracle-flow isolation* experiment answers a narrower question: if the managed
actuator flow were already known exactly, can the hydraulic transition propagate that flow effect
into the next network state?  For a direct reference/candidate pair, the two branches therefore
share the same pre-action hydraulic state, previous managed flow, rainfall and action-context
setting.  The only branch-varying control signal passed into the transition is authoritative
managed flow.

This prevents a hidden ``setting -> typed action message -> state`` bypass from making the oracle
experiment look successful even when ``managed flow -> hydraulics`` is wrong.  It is Development
training/diagnostic infrastructure only; authoritative managed flow is never available online.
"""
from __future__ import annotations

from typing import Any

import torch

ORACLE_FLOW_ISOLATION_CONTRACT = (
    "PROJECT7_V128_ORACLE_MANAGED_FLOW_ONLY_HYDRAULIC_ISOLATION_V1"
)


def shared_reference_setting(setting: torch.Tensor) -> torch.Tensor:
    """Return a two-or-more-branch setting tensor sharing branch-0 action context."""
    if setting.ndim != 2 or int(setting.shape[0]) < 2:
        raise ValueError("oracle direct-effect setting must be [branch, actuator] with >=2 branches")
    return setting[0:1].expand_as(setting)


def oracle_flow_transition_prediction(
    model: Any,
    *,
    prev_state: torch.Tensor,
    previous_flow: torch.Tensor,
    setting: torch.Tensor,
    oracle_flow: torch.Tensor,
    rainfall: torch.Tensor,
    static: dict[str, torch.Tensor],
    action_context_setting: torch.Tensor | None = None,
) -> torch.Tensor:
    """Predict one hydraulic step with authoritative managed flow.

    ``setting`` remains the physically requested action for ordinary teacher-forced A1 samples.
    For direct reference/candidate isolation, pass ``action_context_setting`` generated by
    :func:`shared_reference_setting`; then authoritative managed flow is the only branch-varying
    control signal entering the hydraulic transition.
    """
    if prev_state.ndim != 3 or previous_flow.ndim != 2 or setting.ndim != 2:
        raise ValueError("oracle-flow transition received incompatible state/flow/setting ranks")
    batch = int(prev_state.shape[0])
    if (
        int(previous_flow.shape[0]) != batch
        or int(setting.shape[0]) != batch
        or int(oracle_flow.shape[0]) != batch
        or int(rainfall.shape[0]) != batch
    ):
        raise ValueError("oracle-flow transition batch dimensions differ")
    context_setting = setting if action_context_setting is None else action_context_setting
    if tuple(context_setting.shape) != tuple(setting.shape):
        raise ValueError("oracle action-context setting must match requested setting shape")

    physics_norm, identity = model.actuator.prepare_static(static["physics"], batch_size=batch)
    # Responsiveness is a diagnostic feature of the actuator context, not an authoritative label.
    # Compute it from the same context setting used by the transition so a direct oracle pair has
    # no branch-varying setting side channel.
    with torch.no_grad():
        _, response = model.actuator.forward_prepared(
            prev_state[:, static["up"]],
            prev_state[:, static["down"]],
            context_setting,
            previous_flow,
            physics_norm,
            identity,
        )

    injection = torch.zeros(
        batch,
        prev_state.shape[1],
        1,
        device=prev_state.device,
        dtype=prev_state.dtype,
    )
    injection = injection.index_add(1, static["up"], -oracle_flow[..., None])
    injection = injection.index_add(1, static["down"], oracle_flow[..., None])
    action_context = model._typed_action_context(
        state=prev_state,
        setting=context_setting,
        previous_flow=previous_flow,
        predicted_flow=oracle_flow,
        responsiveness=response.detach(),
        upstream=static["up"],
        downstream=static["down"],
        physics_norm=physics_norm,
        identity_embedding=identity,
    )
    static_norm, edges, inv = model.transition.prepare_static(
        static["static"],
        static["edges"],
        batch_size=batch,
        dtype=prev_state.dtype,
    )
    return model.transition.forward_prepared(
        prev_state,
        rainfall,
        static_norm,
        injection,
        edges,
        inv,
        action_context,
    )


__all__ = [
    "ORACLE_FLOW_ISOLATION_CONTRACT",
    "oracle_flow_transition_prediction",
    "shared_reference_setting",
]
