def test_formal_pipeline_modules_import() -> None:
    import rtc.acceptance_gate  # noqa: F401
    import rtc.baseline_cache  # noqa: F401
    import rtc.baseline_cache_cli  # noqa: F401
    import rtc.calibration_cases  # noqa: F401
    import rtc.causal_timing  # noqa: F401
    import rtc.checkpoint_design  # noqa: F401
    import rtc.context_features  # noqa: F401
    import rtc.d1_exploration  # noqa: F401
    import rtc.d2_eval  # noqa: F401
    import rtc.data_index  # noqa: F401
    import rtc.formal_assets_v2  # noqa: F401
    import rtc.formal_final_v4  # noqa: F401
    import rtc.formal_gradient  # noqa: F401
    import rtc.formal_gradient_v2  # noqa: F401
    import rtc.formal_lock_v5  # noqa: F401
    import rtc.formal_ranking  # noqa: F401
    import rtc.formalize_run  # noqa: F401
    import rtc.forcing  # noqa: F401
    import rtc.inp_audit_v2  # noqa: F401
    import rtc.inp_runtime  # noqa: F401
    import rtc.large_data_cli  # noqa: F401
    import rtc.large_model_cli  # noqa: F401
    import rtc.lazy_step1  # noqa: F401
    import rtc.phase0_timescale  # noqa: F401
    import rtc.priority_resolver  # noqa: F401
    import rtc.production_guard  # noqa: F401
    import rtc.rainfall_design  # noqa: F401
    import rtc.replay_peak  # noqa: F401
    import rtc.runtime_acceptance  # noqa: F401
    import rtc.step2_shards  # noqa: F401
    import rtc.step2_train_v2  # noqa: F401
    import rtc.tfv_mpc  # noqa: F401
    import rtc.tfv_pipeline  # noqa: F401
