"""Fail-closed audit for the V12.2 finite-policy development closed loop.

This is a development evidence checker, not the Formal/Policy-Lock acceptance path.
It understands the V122 first-move adapter (``MPC_V122`` and passive no-benefit
decisions) and verifies that the scored executable first move is the command written
to SWMM without post-score projection.
"""
from __future__ import annotations

import argparse
import csv
import gzip
import hashlib
import json
from pathlib import Path
from typing import Any

import numpy as np

from rtc.code_contract import rtc_source_tree_sha256


def _sha(path: str | Path) -> str:
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def _tfv(path: str | Path) -> float:
    with gzip.open(path, "rt", encoding="utf-8", newline="") as handle:
        return float(sum(float(row["delta_flooding_volume_m3"]) for row in csv.DictReader(handle)))


def _load_decisions(metadata_path: Path) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    meta = json.loads(metadata_path.read_text(encoding="utf-8"))
    if not isinstance(meta, dict):
        raise ValueError("closed-loop metadata must be an object")
    name = meta.get("decision_file")
    if not name:
        raise ValueError("closed-loop metadata lacks decision_file")
    rows = [
        json.loads(line)
        for line in (metadata_path.parent / str(name)).read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    if not all(isinstance(row, dict) for row in rows):
        raise ValueError("decision log contains a non-object row")
    return meta, rows


def audit_v122_closed_loop(
    *,
    metadata_path: str | Path,
    no_control_statistics: str | Path | None = None,
    expected_source_tree_sha256: str | None = None,
) -> dict[str, Any]:
    metadata_path = Path(metadata_path).resolve()
    meta, rows = _load_decisions(metadata_path)
    current_source_sha = rtc_source_tree_sha256()
    if expected_source_tree_sha256 is not None and current_source_sha != expected_source_tree_sha256:
        raise ValueError("current source-tree contract differs from expected SHA")
    if meta.get("rtc_source_tree_sha256") != current_source_sha:
        raise ValueError("closed-loop run was generated by a different source-tree contract")
    if meta.get("strategy") != "proposed":
        raise ValueError("V122 audit requires a Proposed run")
    if int(meta.get("decisions", -1)) != len(rows):
        raise ValueError("metadata decision count differs from decision log")

    start = int(meta.get("control_start_minutes", -1)) * 60
    update = int(meta.get("control_update_seconds", -1))
    if start != 3600 or update != 600:
        raise ValueError("V122 development clock drift")
    if not rows or int(rows[0]["elapsed_seconds"]) != start:
        raise ValueError("first V122 decision is not at the frozen 60-minute epoch")

    source_counts: dict[str, int] = {}
    runtimes: list[float] = []
    predicted: list[float] = []
    non_hold_predicted: list[float] = []
    target_latch_reassertions: list[float] = []
    max_current_delta = 0.0
    max_target_delta = 0.0
    max_planned_delta = 0.0
    score_equals_execute = True
    continuity_pass = True
    target_readback_failures = 0
    fatal_fallbacks = 0
    grid_violations = 0
    candidate_counts: list[int] = []
    first_move_groups: list[int] = []
    tail_only_counts: list[int] = []
    fatal_sources = {
        "FALLBACK_HISTORY_WARMUP",
        "FALLBACK_READBACK",
        "FALLBACK_TARGET_WRITE_READBACK",
        "FALLBACK_RUNTIME_ERROR_V122",
        "FALLBACK_COMPUTE_DEADLINE",
    }
    for row in rows:
        elapsed = int(row.get("elapsed_seconds", -1))
        if elapsed < start or (elapsed - start) % update:
            grid_violations += 1
        source = str(row.get("source", ""))
        source_counts[source] = source_counts.get(source, 0) + 1
        diagnostics = row.get("diagnostics")
        if not isinstance(diagnostics, dict):
            continuity_pass = False
            continue
        if source in fatal_sources:
            fatal_fallbacks += 1
        if diagnostics.get("continuity_guard_passed") is not True:
            continuity_pass = False
        if diagnostics.get("continuity_projection_applied") is not False:
            continuity_pass = False
        if diagnostics.get("score_equals_execute") is not True:
            score_equals_execute = False
        current_delta = float(diagnostics.get("command_delta_from_current_max", np.inf))
        target_delta = float(diagnostics.get("command_delta_from_previous_target_max", np.inf))
        max_current_delta = max(max_current_delta, current_delta)
        max_target_delta = max(max_target_delta, target_delta)
        if not np.isfinite(current_delta) or not np.isfinite(target_delta):
            continuity_pass = False
        if current_delta > 0.5 + 1e-8 or target_delta > 0.5 + 1e-8:
            continuity_pass = False
        planned = diagnostics.get("planned_sequence_max_step_delta")
        if source == "MPC_V122":
            if planned is None or not np.isfinite(float(planned)):
                continuity_pass = False
            else:
                max_planned_delta = max(max_planned_delta, float(planned))
                if float(planned) > 0.5 + 1e-8:
                    continuity_pass = False
            candidate_counts.append(int(diagnostics.get("candidate_count", -1)))
            first_move_groups.append(int(diagnostics.get("first_move_group_count", -1)))
            tail_only_counts.append(int(diagnostics.get("tail_only_noop_candidate_count", -1)))
            value = float(diagnostics.get("predicted_delta_tfv_m3", np.nan))
            if not np.isfinite(value):
                continuity_pass = False
            else:
                predicted.append(value)
                non_hold_predicted.append(value)
        else:
            value = diagnostics.get("predicted_delta_tfv_m3")
            if value is not None and np.isfinite(float(value)):
                predicted.append(float(value))
        reassert = float(diagnostics.get("target_latch_reasserted_max", 0.0))
        if not np.isfinite(reassert) or reassert < 0.0:
            continuity_pass = False
        target_latch_reassertions.append(reassert)
        mismatch = float(diagnostics.get("previous_write_target_readback_mismatch_max", 0.0))
        failed = int(diagnostics.get("target_readback_failed_actuators", 0))
        if mismatch > 1e-6 or failed != 0:
            target_readback_failures += 1

        runtime = diagnostics.get("decision_runtime_seconds")
        if runtime is not None:
            runtime = float(runtime)
            if not np.isfinite(runtime) or runtime < 0.0:
                continuity_pass = False
            else:
                runtimes.append(runtime)

    compact_name = meta.get("compact_file")
    compact_match_max = 0.0
    if compact_name:
        compact_path = metadata_path.parent / str(compact_name)
        if compact_path.is_file():
            compact = np.load(compact_path, allow_pickle=True)
            times = np.asarray(compact["elapsed_seconds"], dtype=np.int64)
            ids = [str(x) for x in compact["actuator_ids"]]
            by_time = {int(t): i for i, t in enumerate(times)}
            target = np.asarray(compact["target_setting"], dtype=np.float64)
            for row in rows:
                t = int(row["elapsed_seconds"])
                if t not in by_time:
                    target_readback_failures += 1
                    continue
                i = by_time[t]
                logged = np.asarray([float(row["settings"][aid]) for aid in ids])
                compact_match_max = max(compact_match_max, float(np.max(np.abs(target[i] - logged))))
            if compact_match_max > 1e-6:
                target_readback_failures += 1

    no_control_tfv = None if no_control_statistics is None else _tfv(no_control_statistics)
    proposed_tfv = None
    statistics_name = meta.get("node_statistics_file")
    if statistics_name:
        statistics_path = metadata_path.parent / str(statistics_name)
        if statistics_path.is_file():
            proposed_tfv = _tfv(statistics_path)
    reduction = None
    if no_control_tfv is not None and proposed_tfv is not None and no_control_tfv:
        reduction = float(100.0 * (no_control_tfv - proposed_tfv) / no_control_tfv)
    max_runtime = float(max(runtimes)) if runtimes else float("inf")
    p95 = float(np.quantile(runtimes, 0.95)) if runtimes else float("inf")
    p99 = float(np.quantile(runtimes, 0.99)) if runtimes else float("inf")
    non_hold_count = source_counts.get("MPC_V122", 0)
    # Descriptive only: no new selection threshold is introduced.  A small-effect
    # tail is reported when the selected predictions themselves approach zero.
    small_effect_tail = [v for v in non_hold_predicted if abs(v) < 1000.0]
    payload: dict[str, Any] = {
        "contract": "PROJECT7_V122_DEVELOPMENT_CLOSED_LOOP_AUDIT_V1",
        "metadata_path": str(metadata_path),
        "source_tree_sha256": current_source_sha,
        "lineage": {
            "step1_model_sha256": meta.get("step1_model_sha256"),
            "step2_model_sha256": meta.get("step2_model_sha256"),
            "graph_schema_sha256": meta.get("graph_schema_sha256"),
            "controller_config_sha256": meta.get("controller_config_sha256"),
            "source_inp_sha256": meta.get("source_inp_sha256"),
            "runtime_inp_sha256": meta.get("inp_sha256"),
        },
        "boundary": {
            "swmm_run": True,
            "new_data_generated": False,
            "step1_retrained": False,
            "step2_retrained": False,
            "validation_accessed": False,
            "final_accessed": False,
            "formal_accessed": False,
            "policy_lock": False,
        },
        "timing": {
            "first_decision_seconds": start,
            "decision_count": len(rows),
            "grid_violations": grid_violations,
            "control_update_seconds": update,
        },
        "sources": source_counts,
        "control": {
            "candidate_count_mpc": sorted(set(candidate_counts)),
            "first_move_group_count_min": min(first_move_groups) if first_move_groups else 0,
            "first_move_group_count_max": max(first_move_groups) if first_move_groups else 0,
            "tail_only_noop_candidate_count_min": min(tail_only_counts) if tail_only_counts else 0,
            "tail_only_noop_candidate_count_max": max(tail_only_counts) if tail_only_counts else 0,
            "score_equals_execute": score_equals_execute,
            "continuity_projection_applied": False,
            "max_command_delta_from_current": max_current_delta,
            "max_command_delta_from_previous_target": max_target_delta,
            "max_planned_sequence_step_delta": max_planned_delta,
            "target_latch_reassertion_max": max(target_latch_reassertions, default=0.0),
            "target_latch_reassertion_decisions": int(sum(x > 1e-9 for x in target_latch_reassertions)),
            "target_readback_failure_count": target_readback_failures,
            "compact_target_vs_logged_command_max": compact_match_max,
        },
        "runtime": {
            "mean_seconds": float(np.mean(runtimes)) if runtimes else float("inf"),
            "median_seconds": float(np.median(runtimes)) if runtimes else float("inf"),
            "p95_seconds": p95,
            "p99_seconds": p99,
            "max_seconds": max_runtime,
            "budget_seconds": 300.0,
            "fatal_fallback_count": fatal_fallbacks,
            "ordinary_passive_fallback_count": int(
                source_counts.get("PASSIVE_MPC_NO_PREDICTED_BENEFIT", 0)
            ),
        },
        "value_behavior": {
            "selected_predicted_delta_tfv_m3": predicted,
            "non_hold_predicted_delta_tfv_m3": non_hold_predicted,
            "small_effect_tail_count_abs_lt_1000_m3": len(small_effect_tail),
            "small_effect_selection_risk": bool(small_effect_tail),
            "small_effect_threshold_is_not_a_gate": True,
        },
        "authoritative_swmm": {
            "proposed_tfv_m3": proposed_tfv,
            "no_control_tfv_m3": no_control_tfv,
            "tfv_reduction_m3": None if reduction is None else float(no_control_tfv - proposed_tfv),
            "tfv_reduction_pct": reduction,
            "global_peak_flood_rate_m3s": meta.get("global_peak_flood_rate_m3s"),
            "flow_routing_error_pct": meta.get("flow_routing_error_pct"),
        },
    }
    payload["passed"] = bool(
        grid_violations == 0
        and fatal_fallbacks == 0
        and target_readback_failures == 0
        and continuity_pass
        and score_equals_execute
        and max_runtime <= 300.0
        and compact_match_max <= 1e-6
    )
    return payload


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--metadata", required=True)
    parser.add_argument("--no-control-statistics")
    parser.add_argument("--out", required=True)
    args = parser.parse_args()
    payload = audit_v122_closed_loop(
        metadata_path=args.metadata,
        no_control_statistics=args.no_control_statistics,
    )
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(payload, indent=2, sort_keys=True))
    if not payload["passed"]:
        raise SystemExit(2)


if __name__ == "__main__":
    main()
