"""Calibrate optimizer-matched admission for refined Direct-TFV first moves."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import numpy as np
import pandas as pd

from rtc.checkpoint_direct_tfv import direct_tfv_first_move_source_sha256
from rtc.direct_tfv_first_move_admission import (
    DIRECT_TFV_FIRST_MOVE_PANEL_CONTRACT,
    DIRECT_TFV_FIRST_MOVE_QUERY_STEP3_CONTRACT,
    derive_first_move_admission,
)
from rtc.step2_train_response_v60 import V60TrainCache


CURRENT_FIRST_MOVE_ADMISSION_RUN_CONTRACT = (
    "PROJECT7_CURRENT_DIRECT_TFV_REFINED_FIRST_MOVE_ADMISSION_CALIBRATION_V1"
)
FIRST_MOVE_CANDIDATE_ROLE = "D3_V9_REFINED_FIRST_MOVE_CALIBRATION_CANDIDATE"


def _sha(path: str | Path) -> str:
    h = hashlib.sha256()
    with Path(path).open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _true_delta(entry, candidate_index: int) -> float:
    arrays = entry.arrays
    reference = int(entry.reference_index)
    ref = float(np.asarray(arrays["exact_node_flood_volume_m3"][reference], dtype=np.float64).sum())
    cand = float(np.asarray(arrays["exact_node_flood_volume_m3"][candidate_index], dtype=np.float64).sum())
    return cand - ref


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--first-move-cache-manifest", required=True)
    p.add_argument("--first-move-design-manifest", required=True)
    p.add_argument("--coverage", type=float, default=0.90)
    p.add_argument("--step2-checkpoint", required=True)
    p.add_argument("--sequence-support", required=True)
    p.add_argument("--out", required=True)
    args = p.parse_args()

    design = pd.read_csv(args.first_move_design_manifest)
    required = {
        "rainfall_group",
        "event_id",
        "checkpoint_id",
        "data_role",
        "sequence_sha256",
        "predicted_refined_delta_tfv_m3",
        "first_move_changed_facility_count",
        "first_move_panel_contract",
        "first_move_query_step3_contract",
        "first_move_source_sha256",
    }
    missing = sorted(required - set(design.columns))
    if missing:
        raise ValueError(f"first-move design manifest missing columns: {missing}")
    candidates = design[design["data_role"].astype(str) == FIRST_MOVE_CANDIDATE_ROLE].copy()
    if candidates.empty:
        raise ValueError("first-move design contains no refined candidates")
    if set(candidates["first_move_panel_contract"].astype(str)) != {DIRECT_TFV_FIRST_MOVE_PANEL_CONTRACT}:
        raise ValueError("first-move design has the wrong panel contract")
    if set(candidates["first_move_query_step3_contract"].astype(str)) != {DIRECT_TFV_FIRST_MOVE_QUERY_STEP3_CONTRACT}:
        raise ValueError("first-move design was generated by a different optimizer contract")
    current_source_sha = direct_tfv_first_move_source_sha256()
    design_source_shas = {str(value).lower() for value in candidates["first_move_source_sha256"]}
    if design_source_shas != {current_source_sha.lower()}:
        raise ValueError(
            "first-move design was generated by a different Direct-TFV first-move source; "
            "regenerate the panel before calibrating admission"
        )
    forbidden = (
        "T5",
        "T10",
        "T20",
        "P15",
        "P35",
        "P75",
        "V10_RP12",
        "V10_RP40",
        "V10_RP90",
        "validation",
        "final",
        "formal",
        "policy_lock",
        "policylock",
    )
    for event in candidates["event_id"].astype(str):
        lowered = event.lower()
        if any(token.lower() in lowered for token in forbidden):
            raise ValueError(f"first-move calibration uses observed/reserved event: {event}")

    expected_groups = sorted({str(value) for value in candidates["rainfall_group"]})
    by_sha = {str(row.sequence_sha256): row for row in candidates.itertuples(index=False)}
    if len(by_sha) != len(candidates):
        raise ValueError("first-move design repeats a candidate sequence SHA")

    cache = V60TrainCache(args.first_move_cache_manifest)
    records: list[dict[str, object]] = []
    seen_groups: set[str] = set()
    for name in cache.names("D3"):
        entry = cache.entry(name)
        roles = {str(role).strip().upper() for role in entry.candidate_roles}
        if roles != {FIRST_MOVE_CANDIDATE_ROLE}:
            raise ValueError(f"{name}: first-move cache has wrong candidate roles: {sorted(roles)}")
        group = str(entry.rainfall_group)
        if group not in set(expected_groups):
            raise ValueError(f"first-move cache contains unexpected rainfall group: {group}")
        candidate_indices = [int(i) for i in entry.indices if int(i) != int(entry.reference_index)]
        if len(candidate_indices) != 1:
            raise ValueError(f"{name}: first-move cache requires exactly one candidate")
        index = candidate_indices[0]
        arrays = entry.arrays
        sha_values = np.asarray(arrays["action_or_sequence_sha256"]).astype(str)
        sequence_sha = str(sha_values[index])
        row = by_sha.get(sequence_sha)
        if row is None:
            raise ValueError(f"{name}: first-move candidate SHA missing from design manifest")
        if str(row.rainfall_group) != group or str(row.event_id) != str(entry.event_id):
            raise ValueError(f"{name}: first-move design/cache identity mismatch")
        records.append(
            {
                "rainfall_group": group,
                "event_id": str(entry.event_id),
                "checkpoint_id": str(entry.checkpoint_id),
                "plan_sha256": sequence_sha,
                "predicted_refined_delta_tfv_m3": float(row.predicted_refined_delta_tfv_m3),
                "true_refined_delta_tfv_m3": _true_delta(entry, index),
                "first_move_changed_facility_count": int(row.first_move_changed_facility_count),
            }
        )
        seen_groups.add(group)
    if seen_groups != set(expected_groups):
        raise ValueError(
            "first-move cache does not cover every design rainfall group; "
            f"missing={sorted(set(expected_groups)-seen_groups)}"
        )

    calibrated = derive_first_move_admission(
        panel_contract=DIRECT_TFV_FIRST_MOVE_PANEL_CONTRACT,
        panel_step3_contract=DIRECT_TFV_FIRST_MOVE_QUERY_STEP3_CONTRACT,
        panel_records=records,
        expected_rainfall_groups=expected_groups,
        coverage=float(args.coverage),
    )
    payload = {
        **calibrated,
        "run_contract": CURRENT_FIRST_MOVE_ADMISSION_RUN_CONTRACT,
        "panel_records": records,
        "lineage": {
            "first_move_source_sha256": current_source_sha,
            "first_move_cache_sha256": _sha(args.first_move_cache_manifest),
            "first_move_design_manifest_sha256": _sha(args.first_move_design_manifest),
            "step2_checkpoint_sha256": _sha(args.step2_checkpoint),
            "sequence_support_sha256": _sha(args.sequence_support),
        },
        "coverage_claim_scope": (
            "90% one-sided finite-sample claim applies to rainfall-group residual maxima of the "
            "same byte-fingerprinted refined first-move optimizer used by Step3 V9"
        ),
    }
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(payload, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
