"""Merge deterministic refined-first-move panel shards after parallel GPU design."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd

from rtc.direct_tfv_first_move_admission import (
    DIRECT_TFV_FIRST_MOVE_MIN_CALIBRATION_GROUPS,
    DIRECT_TFV_FIRST_MOVE_PANEL_CONTRACT,
    DIRECT_TFV_FIRST_MOVE_QUERY_STEP3_CONTRACT,
)


PANEL_RUN_CONTRACT = "PROJECT7_CURRENT_DIRECT_TFV_FIRST_MOVE_PANEL_DESIGN_V1"
MERGE_CONTRACT = "PROJECT7_CURRENT_DIRECT_TFV_FIRST_MOVE_PANEL_MERGE_V1"


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--manifest", action="append", required=True)
    p.add_argument("--summary", action="append", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--summary-out", required=True)
    args = p.parse_args()
    if len(args.manifest) != len(args.summary):
        raise ValueError("one summary is required for each panel manifest shard")
    if len(args.manifest) < 1 or len(args.manifest) > 4:
        raise ValueError("first-move panel merge supports 1-4 shards")

    summaries = [json.loads(Path(path).read_text(encoding="utf-8")) for path in args.summary]
    expected_count = len(summaries)
    shard_indices: set[int] = set()
    groups: set[str] = set()
    lineage = None
    frames: list[pd.DataFrame] = []
    for manifest_path, summary in zip(args.manifest, summaries, strict=True):
        if str(summary.get("contract", "")) != PANEL_RUN_CONTRACT:
            raise ValueError("first-move shard has the wrong run contract")
        if str(summary.get("first_move_panel_contract", "")) != DIRECT_TFV_FIRST_MOVE_PANEL_CONTRACT:
            raise ValueError("first-move shard has the wrong scientific panel contract")
        if str(summary.get("first_move_query_step3_contract", "")) != DIRECT_TFV_FIRST_MOVE_QUERY_STEP3_CONTRACT:
            raise ValueError("first-move shard was generated by a different optimizer")
        if int(summary.get("shard_count", 0)) != expected_count:
            raise ValueError("first-move shard-count metadata differs from supplied shard count")
        index = int(summary.get("shard_index", -1))
        if index < 0 or index >= expected_count or index in shard_indices:
            raise ValueError("first-move shard indices are missing, duplicated or out of range")
        shard_indices.add(index)
        current_lineage = summary.get("lineage")
        if not isinstance(current_lineage, dict):
            raise ValueError("first-move shard lacks lineage")
        if lineage is None:
            lineage = current_lineage
        elif current_lineage != lineage:
            raise ValueError("first-move shard lineage mismatch")
        shard_groups = {str(value) for value in summary.get("rainfall_groups", ())}
        if not shard_groups or groups & shard_groups:
            raise ValueError("first-move shard rainfall groups overlap or are empty")
        groups |= shard_groups
        frame = pd.read_csv(manifest_path)
        if len(frame) != 2 * len(shard_groups):
            raise ValueError("first-move shard row count is not HOLD+candidate per rainfall group")
        frames.append(frame)

    if shard_indices != set(range(expected_count)):
        raise ValueError("first-move shard indices are not exhaustive")
    if len(groups) < DIRECT_TFV_FIRST_MOVE_MIN_CALIBRATION_GROUPS:
        raise ValueError(
            "merged first-move panel requires at least "
            f"{DIRECT_TFV_FIRST_MOVE_MIN_CALIBRATION_GROUPS} rainfall groups; got {len(groups)}"
        )
    frame = pd.concat(frames, ignore_index=True)
    if len(frame) != 2 * len(groups):
        raise ValueError("merged first-move panel does not contain exactly two rows per rainfall group")
    duplicate_sequences = frame[
        frame["data_role"].astype(str) == "D3_V9_REFINED_FIRST_MOVE_CALIBRATION_CANDIDATE"
    ]["sequence_sha256"].astype(str).duplicated()
    if duplicate_sequences.any():
        raise ValueError("merged first-move panel repeats a candidate sequence SHA")

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    frame.to_csv(out, index=False)
    payload = {
        "contract": MERGE_CONTRACT,
        "development_only": True,
        "first_move_panel_contract": DIRECT_TFV_FIRST_MOVE_PANEL_CONTRACT,
        "first_move_query_step3_contract": DIRECT_TFV_FIRST_MOVE_QUERY_STEP3_CONTRACT,
        "shard_count": expected_count,
        "rainfall_group_count": len(groups),
        "rainfall_groups": sorted(groups),
        "rows": len(frame),
        "lineage": lineage,
    }
    summary_out = Path(args.summary_out)
    summary_out.parent.mkdir(parents=True, exist_ok=True)
    summary_out.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(payload, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
