"""Train the Project7 V28R1 supported-manifold residual correction.

This is a compatibility wrapper around the V28 dataset/feature extraction pipeline. It changes
only statistical fitting:

* residual weights on raw->q95 geometry are forced to zero because those fields are not available
  with the same semantics for all historical q95-exact rows;
* ridge and residual shrinkage are selected using Train leakage-group CV only;
* Validation and Test remain report-only;
* alpha=0 exactly recovers frozen Q27.

No SWMM truth is generated by this script.
"""
from __future__ import annotations

import json
from pathlib import Path
import sys
from typing import Any, Sequence

import numpy as np

import train_project7_v28_q95_residual_value as v28train
from rtc.direct_tfv_v28r1_supported_residual import (
    V28R1_SUPPORTED_RESIDUAL_CONTRACT,
    fit_v28r1_supported_residual,
)


V28R1_TRAINING_CONTRACT = (
    "PROJECT7_STEP3_V28R1_SUPPORTED_MANIFOLD_RESIDUAL_TRAIN_CV_ONLY_V1"
)


def _fit_adapter(
    *,
    train_features: np.ndarray,
    train_q27_scores_m3: np.ndarray,
    train_truth_m3: np.ndarray,
    train_groups: Sequence[str],
    train_units: Sequence[str],
    validation_features: np.ndarray,
    validation_q27_scores_m3: np.ndarray,
    validation_truth_m3: np.ndarray,
    validation_units: Sequence[str],
    q27_checkpoint_sha256: str,
    ridge_grid: Sequence[float] | None = None,
) -> tuple[Any, dict[str, Any]]:
    """Accept the V28 trainer signature while forbidding Validation-driven selection."""

    del validation_features, validation_q27_scores_m3, validation_truth_m3, validation_units
    del ridge_grid
    return fit_v28r1_supported_residual(
        train_features=train_features,
        train_q27_scores_m3=train_q27_scores_m3,
        train_truth_m3=train_truth_m3,
        train_groups=train_groups,
        train_units=train_units,
        q27_checkpoint_sha256=q27_checkpoint_sha256,
        cv_folds=5,
    )


def _out_dir_from_argv(argv: Sequence[str]) -> Path | None:
    try:
        index = list(argv).index("--out-dir")
    except ValueError:
        return None
    if index + 1 >= len(argv):
        return None
    return Path(argv[index + 1]).resolve()


def _patch_report(out_dir: Path | None) -> None:
    if out_dir is None:
        return
    path = out_dir / "V28_Q95_MATCHED_RESIDUAL_VALUE_MODEL_REPORT.json"
    if not path.is_file():
        return
    report = json.loads(path.read_text(encoding="utf-8"))
    selection = report.pop("validation_model_selection", None)
    report.update(
        {
            "contract": V28R1_TRAINING_CONTRACT,
            "v28r1_residual_contract": V28R1_SUPPORTED_RESIDUAL_CONTRACT,
            "model_selection_role": "TRAIN_LEAKAGE_GROUP_CV_ONLY",
            "validation_used_for_model_selection": False,
            "validation_report_only": True,
            "test_used_for_training_or_model_selection": False,
            "test_report_only": True,
            "q27_fallback_available_via_residual_shrinkage_zero": True,
        }
    )
    if isinstance(selection, dict):
        report["train_group_cv_model_selection"] = selection
        report["selected_residual_shrinkage"] = float(
            selection.get("selected_residual_shrinkage", 1.0)
        )
    path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def main() -> None:
    v28train.V28_TRAINING_CONTRACT = V28R1_TRAINING_CONTRACT
    v28train.fit_v28_residual_value_model = _fit_adapter
    out_dir = _out_dir_from_argv(sys.argv)
    v28train.main()
    _patch_report(out_dir)


if __name__ == "__main__":
    main()
